import type { Challenge } from "../activities";

export const compositionDockBank: Challenge[] = [
  {
    type: "mc",
    question: "Let f(x) = 2x − 3 and g(x) = x² + 1. What is (f ∘ g)(2)?",
    mathLines: ["(f ∘ g)(2) = f(g(2))"],
    options: ["7", "5", "17", "1"],
    correctIndex: 0,
    explanation: "Apply g first: g(2) = 2² + 1 = 5. Then apply f to that output: f(5) = 2(5) − 3 = 7. Therefore, (f ∘ g)(2) = 7.",
    hint: "The function closest to the input, g, acts first.",
  },
  {
    type: "fill",
    question: "Let f(x) = x + 4 and g(x) = 3x². Find (g ∘ f)(−2).",
    mathLines: ["(g ∘ f)(−2) = g(f(−2))"],
    answer: "12",
    accepted: ["12"],
    explanation: "First, f(−2) = −2 + 4 = 2. Next, g(2) = 3(2²) = 12. Thus (g ∘ f)(−2) = 12.",
    hint: "Evaluate f at −2 before using g.",
  },
  {
    type: "mc",
    question: "Let f(x) = √x and g(x) = x + 1. What is (f ∘ g)(8)?",
    mathLines: ["(f ∘ g)(8) = f(g(8))"],
    options: ["3", "√8 + 1", "9", "81"],
    correctIndex: 0,
    explanation: "The inner function gives g(8) = 8 + 1 = 9. Applying f next gives f(9) = √9 = 3. Therefore, (f ∘ g)(8) = 3.",
    hint: "Add 1 first, then take the square root.",
  },
  {
    type: "fill",
    question: "Let f(x) = 3x − 2 and g(x) = x² + 5. Write (g ∘ f)(x) without expanding.",
    mathLines: ["(g ∘ f)(x) = g(f(x))", "= g(3x − 2)"],
    answer: "(3x-2)^2+5",
    accepted: ["(3x-2)^2+5", "(3x − 2)² + 5", "(3x-2)²+5", "(3x − 2)^2 + 5"],
    explanation: "Because g(u) = u² + 5, substitute the entire expression f(x) = 3x − 2 for u. This gives g(f(x)) = (3x − 2)² + 5.",
    hint: "Put the complete output 3x − 2 into every input position of g.",
  },
  {
    type: "mc",
    question: "Let f(x) = x² and g(x) = 2x + 1. Which expression is (f ∘ g)(x)?",
    mathLines: ["(f ∘ g)(x) = f(g(x))"],
    options: ["(2x + 1)²", "2x² + 1", "4x² + 1", "x² + 2x + 1"],
    correctIndex: 0,
    explanation: "The output of g is 2x + 1, and f squares its input. Therefore f(g(x)) = f(2x + 1) = (2x + 1)². The option x² + 2x + 1 incorrectly squares only part of the input.",
    hint: "Since f squares its whole input, use parentheses around g(x).",
  },
  {
    type: "fill",
    question: "Let g(x) = 3 − x. Use the piecewise function f below to find (f ∘ g)(5).",
    piecewise: {
      label: "f(x) =",
      cases: [
        { expression: "2x + 1", condition: "x < 0" },
        { expression: "x²", condition: "x ≥ 0" },
      ],
    },
    mathLines: ["(f ∘ g)(5) = f(g(5))"],
    answer: "-3",
    accepted: ["-3", "−3"],
    explanation: "Compute the inner output first: g(5) = 3 − 5 = −2. Since −2 is in the x < 0 case, f(−2) = 2(−2) + 1 = −3. Hence (f ∘ g)(5) = −3.",
    hint: "Find g(5), then use that result to choose the correct case of f.",
  },
  {
    type: "mc",
    question: "Let f(x) = √x and g(x) = x − 4. What is the domain of (f ∘ g)(x)? Give the domain in interval notation.",
    mathLines: ["(f ∘ g)(x) = √(x − 4)"],
    options: ["(−∞, 4]", "(4, ∞)", "[4, ∞)", "(−∞, ∞)"],
    correctIndex: 2,
    explanation: "The square-root input x − 4 must be nonnegative. This occurs starting at 4, and 4 is allowed because √0 exists. Thus the domain is [4, ∞).",
    hint: "A real square root permits zero inside but not a negative value.",
  },
  {
    type: "fill",
    question: "Let f(x) = 1/(x + 1) and g(x) = √(x − 2). Find the domain of (f ∘ g)(x) in interval notation.",
    mathLines: ["(f ∘ g)(x) = 1/(√(x − 2) + 1)"],
    answer: "[2,∞)",
    accepted: ["[2,∞)", "[2, ∞)"],
    explanation: "The inner square root is defined beginning at 2. On that interval, √(x − 2) is never negative, so √(x − 2) + 1 is always positive and cannot be zero. Therefore the domain is [2, ∞).",
    hint: "Check both the square root and whether the composite denominator can be zero.",
  },
  {
    type: "mc",
    question: "Let f(x) = √(x + 1) and g(x) = 1/(x − 3). What is the domain of (g ∘ f)(x)? Give the domain in interval notation.",
    mathLines: ["(g ∘ f)(x) = 1/(√(x + 1) − 3)"],
    options: ["[−1, ∞)", "[−1, 8) ∪ (8, ∞)", "(−1, 8) ∪ (8, ∞)", "[−1, 8]"],
    correctIndex: 1,
    explanation: "First, √(x + 1) requires x to start at −1. The outer denominator is zero when √(x + 1) = 3, which happens at x = 8, so that one input must be removed. The domain is [−1, 8) ∪ (8, ∞).",
    hint: "Keep inputs that make the square root real, then remove the input that makes the outer denominator zero.",
  },
  {
    type: "fill",
    question: "Let f(x) = ln(x) and g(x) = 5 − x. Find the domain of (f ∘ g)(x) in interval notation.",
    mathLines: ["(f ∘ g)(x) = ln(5 − x)"],
    answer: "(-∞,5)",
    accepted: ["(-∞,5)", "(−∞,5)", "(−∞, 5)"],
    explanation: "A logarithm accepts only positive inputs. The quantity 5 − x is positive for inputs to the left of 5, while x = 5 would make the logarithm input zero. Therefore the domain is (−∞, 5).",
    hint: "The input to ln must be positive, not merely nonnegative.",
  },
  {
    type: "mc",
    question: "Let f(x) = 1/x and g(x) = x² − 9. What is the domain of (f ∘ g)(x)? Give the domain in interval notation.",
    mathLines: ["(f ∘ g)(x) = 1/(x² − 9)"],
    options: ["(−∞, −3) ∪ (−3, 3) ∪ (3, ∞)", "(−∞, ∞)", "[−3, 3]", "(−3, 3)"],
    correctIndex: 0,
    explanation: "The denominator x² − 9 factors as (x − 3)(x + 3), so it is zero at −3 and 3. All other real inputs are permitted. The domain is (−∞, −3) ∪ (−3, 3) ∪ (3, ∞).",
    hint: "A reciprocal cannot have a zero denominator; factor the denominator to find its zeros.",
  },
  {
    type: "fill",
    question: "Let f(x) = √(7 − x) and g(x) = 2x + 1. Find the domain of (f ∘ g)(x) in interval notation.",
    mathLines: ["(f ∘ g)(x) = √(7 − (2x + 1))", "= √(6 − 2x)"],
    answer: "(-∞,3]",
    accepted: ["(-∞,3]", "(−∞,3]", "(−∞, 3]"],
    explanation: "For the composite square root to be real, 6 − 2x must be nonnegative. Its zero occurs at x = 3, and inputs no greater than 3 make the radicand nonnegative. Hence the domain is (−∞, 3].",
    hint: "Set the radicand boundary equal to zero, then test which side keeps it nonnegative.",
  },
  {
    type: "mc",
    question: "Let f(x) = x² and g(x) = √(4 − x). What is the domain of (g ∘ f)(x)? Give the domain in interval notation.",
    mathLines: ["(g ∘ f)(x) = √(4 − x²)"],
    options: ["(−2, 2)", "(−∞, −2] ∪ [2, ∞)", "[−2, 2]", "(−∞, ∞)"],
    correctIndex: 2,
    explanation: "The radicand 4 − x² is nonnegative from −2 through 2, including both endpoints because it equals zero there. Therefore the domain of the composite is [−2, 2].",
    hint: "Find where x² does not exceed 4, and remember that a zero radicand is allowed.",
  },
  {
    type: "fill",
    question: "Let f(x) = 1/(x − 2) and g(x) = √x. Find the domain of (f ∘ g)(x) in interval notation.",
    mathLines: ["(f ∘ g)(x) = 1/(√x − 2)"],
    answer: "[0,4)∪(4,∞)",
    accepted: ["[0,4)∪(4,∞)", "[0, 4) ∪ (4, ∞)"],
    explanation: "The inner square root permits inputs from 0 onward. The outer denominator becomes zero when √x = 2, which occurs at x = 4, so 4 is removed. The domain is [0, 4) ∪ (4, ∞).",
    hint: "Start with the square-root restriction, then exclude the value that makes √x − 2 equal zero.",
  },
  {
    type: "mc",
    question: "Let f(x) = ln(x − 1) and g(x) = 1/(x + 2). What is the domain of (f ∘ g)(x)? Give the domain in interval notation.",
    mathLines: ["(f ∘ g)(x) = ln(1/(x + 2) − 1)", "= ln((−x − 1)/(x + 2))"],
    options: ["(−∞, −2) ∪ (−1, ∞)", "(−2, −1)", "[−2, −1]", "(−∞, −1)"],
    correctIndex: 1,
    explanation: "The input to ln must be positive. For (−x − 1)/(x + 2), the numerator and denominator have the same sign only between the critical inputs −2 and −1. Neither endpoint is allowed: at −2 the fraction is undefined, and at −1 it equals zero. Thus the domain is (−2, −1).",
    hint: "Use the two critical inputs −2 and −1 to make a sign chart for the logarithm’s input.",
  },
  {
    type: "fill",
    question: "Let f(x) = √(x + 2) and g(x) = 1/(x − 1). Find the domain of (f ∘ g)(x) in interval notation.",
    mathLines: ["(f ∘ g)(x) = √(1/(x − 1) + 2)", "= √((2x − 1)/(x − 1))"],
    answer: "(-∞,1/2]∪(1,∞)",
    accepted: ["(-∞,1/2]∪(1,∞)", "(−∞, 1/2] ∪ (1, ∞)", "(−∞,1/2] ∪ (1,∞)"],
    explanation: "The square-root input must be nonnegative, and x = 1 is excluded because g is undefined there. A sign chart for (2x − 1)/(x − 1), using critical inputs 1/2 and 1, is nonnegative on the interval ending at 1/2 and again to the right of 1. Thus the domain is (−∞, 1/2] ∪ (1, ∞).",
    hint: "The numerator is zero at 1/2 and the denominator is zero at 1; use those points to split a sign chart.",
  },
  {
    type: "mc",
    question: "Let f(x) = x − 5 and g(x) = 1/x. What is (g ∘ f)(7)?",
    mathLines: ["(g ∘ f)(7) = g(f(7))"],
    options: ["1/2", "2", "−1/2", "1/7 − 5"],
    correctIndex: 0,
    explanation: "First f(7) = 7 − 5 = 2. Then g(2) = 1/2. Therefore (g ∘ f)(7) = 1/2.",
    hint: "Subtract 5 before taking the reciprocal.",
  },
  {
    type: "fill",
    question: "Let f(x) = 2x + 1 and g(x) = x² − 4. Write (f ∘ g)(x) in simplified form.",
    mathLines: ["(f ∘ g)(x) = f(g(x))", "= f(x² − 4)"],
    answer: "2x^2-7",
    accepted: ["2x^2-7", "2x²−7", "2x² - 7", "2x^2 - 7"],
    explanation: "Substitute g(x) = x² − 4 into f: f(x² − 4) = 2(x² − 4) + 1 = 2x² − 8 + 1 = 2x² − 7.",
    hint: "Replace the input x in 2x + 1 with the entire expression x² − 4.",
  },
  {
    type: "mc",
    question: "A table gives f(1) = 4, f(2) = −1, and f(3) = 0. If g(x) = x + 6, what is (g ∘ f)(2)?",
    mathLines: ["(g ∘ f)(2) = g(f(2))"],
    options: ["5", "−7", "8", "1"],
    correctIndex: 0,
    explanation: "From the table, f(2) = −1. Applying g gives g(−1) = −1 + 6 = 5. Therefore (g ∘ f)(2) = 5.",
    hint: "Read f(2) from the table before using the rule for g.",
  },
  {
    type: "fill",
    question: "Let f(x) = x² and g(x) = √x. Simplify (g ∘ f)(x).",
    mathLines: ["(g ∘ f)(x) = g(f(x))", "= √(x²)"],
    answer: "|x|",
    accepted: ["|x|", "abs(x)", "absolute value of x"],
    explanation: "Substitution gives √(x²). A square root represents the nonnegative root, so √(x²) equals |x| rather than x for every real x. Hence (g ∘ f)(x) = |x|.",
    hint: "The principal square root is never negative.",
  },
];
