import type { Challenge } from "../activities";

export const frontierFinalBank: Challenge[] = [
  // 1. Function Scout — definitions and identification
  {
    type: "mc",
    question: "Which relation is a function?",
    options: [
      "{(−2, 1), (−2, 4), (3, 0)}",
      "{(1, 5), (1, −5), (2, 3)}",
      "{(−1, 2), (0, 2), (4, −3)}",
      "{(0, 1), (2, 3), (0, 5)}",
    ],
    correctIndex: 2,
    explanation: "A relation is a function when every input is paired with exactly one output. In {(−1, 2), (0, 2), (4, −3)}, the inputs −1, 0, and 4 each occur once. Repeated outputs, such as 2, are allowed.",
    hint: "Check whether any x-value is paired with two different y-values.",
  },
  {
    type: "fill",
    question: "For f(x) = 3x² − 2x + 1, find f(−2).",
    mathLines: ["f(−2) = 3(−2)² − 2(−2) + 1"],
    answer: "17",
    accepted: ["17"],
    explanation: "Substituting −2 for every x gives f(−2) = 3(4) + 4 + 1 = 17.",
    hint: "Use parentheses around the negative input before squaring.",
  },
  {
    type: "mc",
    question: "A relation assigns the output 6 to input 2 and the output −1 to input 5. Which statement is true?",
    options: [
      "The relation contains the point (6, 2).",
      "The relation contains the point (−1, 5).",
      "The relation contains the points (2, 6) and (5, −1).",
      "The relation cannot be a function because its outputs differ.",
    ],
    correctIndex: 2,
    explanation: "Ordered pairs list input first and output second. Therefore, the two assignments are represented by (2, 6) and (5, −1). Different outputs for different inputs do not violate the definition of a function.",
    hint: "Write each assignment as (input, output).",
  },
  {
    type: "fill",
    question: "Is the relation {(−3, 4), (0, 4), (2, −1)} a function? Enter yes or no.",
    answer: "yes",
    accepted: ["yes", "Yes", "YES"],
    explanation: "Yes. The inputs are −3, 0, and 2, and each is associated with one output. The fact that −3 and 0 both have output 4 is permitted for a function.",
    hint: "A repeated output is allowed; a repeated input with different outputs is not.",
  },

  // 2. Representation Relay — tables, notation, and rules
  {
    type: "mc",
    question: "A table for f gives the inputs and outputs below. Which rule matches every row?",
    mathLines: ["x:  −1     0     2", "f(x):  5     3    −1"],
    options: ["f(x) = 2x + 3", "f(x) = −2x + 3", "f(x) = x² + 3", "f(x) = −x + 4"],
    correctIndex: 1,
    explanation: "From x = 0, the output is 3, so the constant term is 3. Each increase of 1 in x changes the output by −2, giving f(x) = −2x + 3. Checking x = 2 gives −4 + 3 = −1.",
    hint: "Use the row with x = 0 for the intercept, then compare the rate of change.",
  },
  {
    type: "fill",
    question: "If h(t) = t² + 2, write h(a − 1) in simplified form.",
    mathLines: ["h(a − 1) = (a − 1)² + 2"],
    answer: "a^2-2a+3",
    accepted: ["a²−2a+3", "a^2-2a+3", "a² - 2a + 3", "a^2 - 2a + 3"],
    explanation: "Replace t by the entire input a − 1: h(a − 1) = (a − 1)² + 2 = a² − 2a + 1 + 2 = a² − 2a + 3.",
    hint: "Square the entire binomial (a − 1), not just a.",
  },
  {
    type: "mc",
    question: "If p(4) = −1, which point lies on the graph of p?",
    options: ["(−1, 4)", "(4, −1)", "(4, 1)", "(−4, −1)"],
    correctIndex: 1,
    explanation: "The notation p(4) = −1 says that input 4 produces output −1. A graph records this as the ordered pair (4, −1).",
    hint: "Function notation has the form function(input) = output.",
  },
  {
    type: "fill",
    question: "Use the table to find q(−3).",
    mathLines: ["x:     −3      1      5", "q(x):    8     −2      0"],
    answer: "8",
    accepted: ["8"],
    explanation: "The column whose input is −3 has output 8, so q(−3) = 8.",
    hint: "Read the output in the same column as x = −3.",
  },

  // 3. Interval Observatory — domain and range
  {
    type: "fill",
    question: "Find the domain of r(x) = √(7 − 2x). Use interval notation.",
    answer: "(−∞, 7/2]",
    accepted: ["(−∞, 7/2]", "(-∞, 7/2]", "(−∞,7/2]", "(-∞,7/2]"],
    explanation: "The radicand 7 − 2x is zero at x = 7/2 and is nonnegative for inputs to the left of that point. Thus the domain is (−∞, 7/2].",
    hint: "A real square root needs a nonnegative radicand; locate where 7 − 2x becomes zero.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "What is the range of s(x) = −(x − 1)² + 4? Use interval notation.",
    options: ["[4, ∞)", "(−∞, 4]", "(−∞, 4)", "[−4, ∞)"],
    correctIndex: 1,
    explanation: "Because (x − 1)² is at least 0, −(x − 1)² is at most 0. Adding 4 makes 4 the greatest output, attained at x = 1; outputs extend without bound downward. The range is (−∞, 4].",
    hint: "Identify the vertex and whether the parabola opens upward or downward.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "Find the domain of q(x) = √(x + 1)/(x − 3). Use interval notation.",
    answer: "[−1, 3) ∪ (3, ∞)",
    accepted: ["[−1, 3) ∪ (3, ∞)", "[-1, 3) ∪ (3, ∞)", "[−1,3)∪(3,∞)", "[-1,3)U(3,infinity)"],
    explanation: "The square root begins at x = −1, so −1 is included. The denominator is zero at x = 3, so that input is excluded. Combining these restrictions gives [−1, 3) ∪ (3, ∞).",
    hint: "Account for both the square-root restriction and the denominator restriction.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "What is the domain of u(x) = 1/(x² − 4)? Use interval notation.",
    options: [
      "(−∞, −2] ∪ [2, ∞)",
      "(−∞, −2) ∪ (−2, 2) ∪ (2, ∞)",
      "(−2, 2)",
      "(−∞, ∞)",
    ],
    correctIndex: 1,
    explanation: "The denominator factors as x² − 4 = (x − 2)(x + 2). It is zero at x = −2 and x = 2, so both inputs are excluded. The domain is (−∞, −2) ∪ (−2, 2) ∪ (2, ∞).",
    hint: "Factor the denominator and exclude its zeros.",
    visual: "domain",
  },

  // 4. Piecewise Dispatch — selecting and checking rules
  {
    type: "fill",
    question: "Find f(−4).",
    piecewise: {
      label: "f(x) =",
      cases: [
        { expression: "2x + 1", condition: "x < 0" },
        { expression: "x² − 1", condition: "x ≥ 0" },
      ],
    },
    answer: "−7",
    accepted: ["−7", "-7"],
    explanation: "Since −4 < 0, the active rule is f(x) = 2x + 1. Therefore f(−4) = 2(−4) + 1 = −7.",
    hint: "First decide which condition contains −4.",
    visual: "piecewise",
  },
  {
    type: "mc",
    question: "For the function below, what is f(2)?",
    piecewise: {
      label: "f(x) =",
      cases: [
        { expression: "x + 1", condition: "x ≤ 2" },
        { expression: "x² − 3", condition: "x > 2" },
      ],
    },
    options: ["1", "3", "4", "7"],
    correctIndex: 1,
    explanation: "The input 2 satisfies x ≤ 2, so use f(x) = x + 1. Then f(2) = 2 + 1 = 3. The second rule does not include x = 2.",
    hint: "Notice which condition includes the endpoint 2.",
    visual: "piecewise",
  },
  {
    type: "fill",
    question: "Find m(5).",
    piecewise: {
      label: "m(x) =",
      cases: [
        { expression: "3 − x", condition: "x < 3" },
        { expression: "2x − 3", condition: "x ≥ 3" },
      ],
    },
    answer: "7",
    accepted: ["7"],
    explanation: "Because 5 is at least 3, use m(x) = 2x − 3. Thus m(5) = 2(5) − 3 = 7.",
    hint: "The rule changes at x = 3; compare 5 with 3.",
    visual: "piecewise",
  },
  {
    type: "mc",
    question: "Which conclusion about the function below at x = 1 is justified?",
    piecewise: {
      label: "k(x) =",
      cases: [
        { expression: "x²", condition: "x < 1" },
        { expression: "2x − 1", condition: "x ≥ 1" },
      ],
    },
    options: [
      "k is discontinuous at x = 1 because different rules are used.",
      "k is continuous at x = 1 because both rules give 1 there and k(1) = 1.",
      "k(1) = 0 because the first rule is evaluated at x = 1.",
      "k has no value at x = 1.",
    ],
    correctIndex: 1,
    explanation: "Approaching from the left, x² approaches 1 at x = 1. The active rule at 1 is 2x − 1, which gives k(1) = 2(1) − 1 = 1. The matching left-hand value, right-hand value, and function value prove continuity at x = 1.",
    hint: "Evaluate the first expression at the boundary as a left-hand check, then use the condition that includes 1 for k(1).",
    visual: "piecewise",
  },

  // 5. Terrain Analyzer — extrema and monotonicity
  {
    type: "mc",
    question: "On the closed interval [−1, 4], what is the absolute maximum value of f(x) = −x² + 4x + 1?",
    mathLines: ["f(−1) = −4", "f(2) = 5", "f(4) = 1"],
    options: ["2", "5", "(2, 5)", "1"],
    correctIndex: 1,
    explanation: "The vertex occurs at x = −b/(2a) = −4/(2·−1) = 2. Comparing the endpoint and vertex values shown gives −4, 5, and 1. The greatest output is 5, so the absolute maximum value is 5, not the point (2, 5).",
    hint: "On a closed interval, compare both endpoints and the vertex; the question asks for a value, not a point.",
    visual: "terrain",
  },
  {
    type: "fill",
    question: "On the closed interval [−2, 3], give the absolute minimum point of g(x) = (x − 1)² − 4.",
    mathLines: ["g(−2) = 5", "g(1) = −4", "g(3) = 0"],
    answer: "(1, −4)",
    accepted: ["(1, −4)", "(1,-4)", "(1,−4)"],
    explanation: "The parabola opens upward, and its vertex is at x = 1. Comparing g(−2) = 5, g(1) = −4, and g(3) = 0 shows that the least output is −4 at x = 1. Therefore the absolute minimum point is (1, −4).",
    hint: "A point includes both the x-coordinate and y-coordinate.",
    visual: "terrain",
  },
  {
    type: "mc",
    question: "A continuous function is increasing on [0, 2], decreasing on [2, 4], and increasing on [4, 6]. It has f(2) = 7 and f(4) = 3. Which statement is correct?",
    options: [
      "(2, 7) is a local minimum and (4, 3) is a local maximum.",
      "(2, 7) is a local maximum and (4, 3) is a local minimum.",
      "Both points are local maxima.",
      "Neither point is a local extremum.",
    ],
    correctIndex: 1,
    explanation: "At x = 2, the function changes from increasing to decreasing, so nearby values are lower: (2, 7) is a local maximum. At x = 4, it changes from decreasing to increasing, so nearby values are higher: (4, 3) is a local minimum.",
    hint: "Increasing then decreasing signals a local maximum; decreasing then increasing signals a local minimum.",
    visual: "terrain",
  },
  {
    type: "fill",
    question: "A continuous function f is decreasing on [−3, 0], increasing on [0, 1], and decreasing on [1, 4]. Given f(−3) = 6, f(0) = 2, f(1) = 5, and f(4) = 8, give the absolute maximum point on [−3, 4].",
    answer: "(4, 8)",
    accepted: ["(4, 8)", "(4,8)"],
    explanation: "For an absolute extremum on a closed interval, compare endpoints as well as turning points. The relevant values are 6 at x = −3, 2 at x = 0, 5 at x = 1, and 8 at x = 4. The greatest is 8, so the absolute maximum point is the endpoint (4, 8).",
    hint: "Do not omit endpoints when finding an absolute extremum on a closed interval.",
    visual: "terrain",
  },

  // 6. Symmetry Scanner — even, odd, and neither
  {
    type: "mc",
    question: "Classify f(x) = x⁴ − 5x² as even, odd, or neither.",
    options: ["even", "odd", "neither", "both even and odd"],
    correctIndex: 0,
    explanation: "f(−x) = (−x)⁴ − 5(−x)² = x⁴ − 5x² = f(x). Since replacing x by −x leaves the rule unchanged, f is even.",
    hint: "For an even function, test whether f(−x) equals f(x).",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "For g(x) = x³ − 4x, simplify g(−x).",
    mathLines: ["g(−x) = (−x)³ − 4(−x)"],
    answer: "-x^3+4x",
    accepted: ["−x³+4x", "-x^3+4x", "−x³ + 4x", "-x^3 + 4x"],
    explanation: "Substitution gives g(−x) = −x³ + 4x = −(x³ − 4x) = −g(x). This also proves that g is odd.",
    hint: "Odd powers preserve the negative sign; then distribute the coefficient −4.",
    visual: "symmetry",
  },
  {
    type: "mc",
    question: "Classify h(x) = x³ + x² as even, odd, or neither.",
    options: ["even", "odd", "neither", "both even and odd"],
    correctIndex: 2,
    explanation: "h(−x) = −x³ + x². This is not equal to h(x) = x³ + x² and not equal to −h(x) = −x³ − x². Therefore h is neither even nor odd.",
    hint: "Compare h(−x) with both h(x) and −h(x).",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "Function p is even and p(3) = −7. Find p(−3).",
    answer: "−7",
    accepted: ["−7", "-7"],
    explanation: "For an even function, p(−x) = p(x). Thus p(−3) = p(3) = −7.",
    hint: "Even functions have matching outputs at opposite inputs.",
    visual: "symmetry",
  },

  // 7. Rate-of-Change Lab — average rate and difference quotient
  {
    type: "mc",
    question: "What is the average rate of change of f(x) = x² + 1 from x = −1 to x = 3?",
    mathLines: ["[f(3) − f(−1)] / [3 − (−1)]"],
    options: ["−2", "2", "4", "8"],
    correctIndex: 1,
    explanation: "f(3) = 10 and f(−1) = 2. Therefore the average rate of change is (10 − 2)/(3 − (−1)) = 8/4 = 2.",
    hint: "Compute the change in output and divide by the change in input.",
  },
  {
    type: "fill",
    question: "Simplify the difference quotient [f(x + h) − f(x)]/h for f(x) = x² − 5x.",
    mathLines: ["f(x + h) = (x + h)² − 5(x + h)", "[f(x + h) − f(x)]/h"],
    answer: "2x+h-5",
    accepted: ["2x+h−5", "2x+h-5", "2x + h − 5", "2x + h - 5"],
    explanation: "Substitute and simplify: [(x + h)² − 5(x + h) − (x² − 5x)]/h = [2xh + h² − 5h]/h = h(2x + h − 5)/h = 2x + h − 5.",
    hint: "Expand (x + h)², then factor h from every remaining term in the numerator.",
  },
  {
    type: "mc",
    question: "For p(x) = 2x − 7, what is the average rate of change from x = 4 to x = 10?",
    options: ["−7", "2", "6", "13"],
    correctIndex: 1,
    explanation: "p(4) = 1 and p(10) = 13, so the average rate of change is (13 − 1)/(10 − 4) = 12/6 = 2. This equals the slope of the linear function.",
    hint: "A linear function has the same rate of change over every interval.",
  },
  {
    type: "fill",
    question: "Find the average rate of change of r(t) = 1/t from t = 1 to t = 4.",
    mathLines: ["[r(4) − r(1)] / (4 − 1)"],
    answer: "−1/4",
    accepted: ["−1/4", "-1/4"],
    explanation: "r(4) = 1/4 and r(1) = 1. Thus [1/4 − 1]/3 = (−3/4)/3 = −1/4.",
    hint: "Subtract the function values before dividing by the input change of 3.",
  },

  // 8. Transformation Bay — translations, reflections, and stretches
  {
    type: "mc",
    question: "Relative to y = f(x), how is y = f(x − 3) + 2 transformed?",
    options: ["left 3 units and up 2 units", "right 3 units and up 2 units", "right 2 units and up 3 units", "left 3 units and down 2 units"],
    correctIndex: 1,
    explanation: "Replacing x by x − 3 shifts the graph right 3 units because the input must be 3 larger to produce the same original output. Adding 2 outside the function shifts it up 2 units.",
    hint: "Changes inside f affect horizontal position in the opposite apparent direction.",
    visual: "transform",
  },
  {
    type: "fill",
    question: "Give the vertex of y = −2(x + 1)² + 5.",
    answer: "(−1, 5)",
    accepted: ["(−1, 5)", "(-1, 5)", "(−1,5)", "(-1,5)"],
    explanation: "Vertex form is y = a(x − h)² + k, whose vertex is (h, k). Here x + 1 = x − (−1), so h = −1 and k = 5. The factor −2 changes opening and vertical scale, not the vertex.",
    hint: "Rewrite x + 1 mentally as x − (−1).",
    visual: "transform",
  },
  {
    type: "mc",
    question: "The point (2, −3) lies on y = f(x). Which point lies on y = 3f(−x) + 1?",
    options: ["(2, −8)", "(−2, −8)", "(−2, −2)", "(2, −2)"],
    correctIndex: 1,
    explanation: "The −x inside reflects the input across the y-axis, sending x = 2 to x = −2. The output changes from −3 to 3(−3) + 1 = −8. Thus the transformed point is (−2, −8).",
    hint: "Handle the input reflection first, then apply the outside output transformation.",
    visual: "transform",
  },
  {
    type: "fill",
    question: "Starting with f(x) = √x, write g(x) for the graph shifted right 4 units and down 2 units.",
    answer: "√(x−4)−2",
    accepted: ["√(x−4)−2", "sqrt(x-4)-2", "√(x - 4) - 2", "sqrt(x - 4) - 2"],
    explanation: "A shift right 4 replaces x by x − 4, and a shift down 2 subtracts 2 outside the function. Therefore g(x) = √(x − 4) − 2.",
    hint: "A horizontal right shift changes the input; a downward shift changes the output.",
    visual: "transform",
  },

  // 9. Operation Forge — sum, product, difference, quotient
  {
    type: "mc",
    question: "Let f(x) = 2x + 1 and g(x) = x² − 4. What is (f + g)(3)?",
    mathLines: ["(f + g)(3) = f(3) + g(3)"],
    options: ["2", "7", "12", "16"],
    correctIndex: 2,
    explanation: "f(3) = 2(3) + 1 = 7 and g(3) = 3² − 4 = 5. Hence (f + g)(3) = 7 + 5 = 12.",
    hint: "Evaluate both named functions at 3 before adding.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f(x) = x − 2 and g(x) = x + 5. Write (fg)(x) in simplified form.",
    mathLines: ["(fg)(x) = f(x)g(x) = (x − 2)(x + 5)"],
    answer: "x^2+3x-10",
    accepted: ["x²+3x−10", "x^2+3x-10", "x² + 3x − 10", "x^2 + 3x - 10"],
    explanation: "Multiplying gives (x − 2)(x + 5) = x² + 5x − 2x − 10 = x² + 3x − 10.",
    hint: "Use distribution or FOIL to multiply the two binomials.",
    visual: "operations",
  },
  {
    type: "mc",
    question: "Let f(x) = √(x + 1) and g(x) = x − 2. What is the domain of (f/g)(x)? Use interval notation.",
    options: ["[−1, ∞)", "(−∞, 2) ∪ (2, ∞)", "[−1, 2) ∪ (2, ∞)", "[−1, 2]"],
    correctIndex: 2,
    explanation: "The square root permits inputs beginning at −1. The quotient also excludes x = 2 because g(2) = 0. Therefore the domain is [−1, 2) ∪ (2, ∞).",
    hint: "A quotient must satisfy the restrictions of both functions, and its denominator cannot be zero.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f(x) = 3x² − 1 and g(x) = x² + 4x. Write (f − g)(x) in simplified form.",
    mathLines: ["(f − g)(x) = (3x² − 1) − (x² + 4x)"],
    answer: "2x^2-4x-1",
    accepted: ["2x²−4x−1", "2x^2-4x-1", "2x² - 4x - 1", "2x^2 - 4x - 1"],
    explanation: "Distribute the subtraction across g(x): 3x² − 1 − x² − 4x = 2x² − 4x − 1.",
    hint: "The minus sign changes the sign of every term inside g(x).",
    visual: "operations",
  },

  // 10. Composition Dock — nested functions and composite domains
  {
    type: "mc",
    question: "Let f(x) = 2x − 1 and g(x) = x² + 3. What is (f ∘ g)(2)?",
    mathLines: ["(f ∘ g)(2) = f(g(2))"],
    options: ["7", "9", "13", "25"],
    correctIndex: 2,
    explanation: "First apply g: g(2) = 2² + 3 = 7. Then apply f to that output: f(7) = 2(7) − 1 = 13. Therefore (f ∘ g)(2) = 13.",
    hint: "In f ∘ g, g acts first because it is inside f.",
  },
  {
    type: "fill",
    question: "Let f(x) = √(x + 4) and g(x) = 2x − 5. Write (f ∘ g)(x) in simplified form.",
    mathLines: ["(f ∘ g)(x) = f(g(x)) = f(2x − 5)"],
    answer: "√(2x−1)",
    accepted: ["√(2x−1)", "sqrt(2x-1)", "√(2x - 1)", "sqrt(2x - 1)"],
    explanation: "Substitute g(x) = 2x − 5 for the input of f: f(g(x)) = √[(2x − 5) + 4] = √(2x − 1).",
    hint: "Replace the input x in f(x) with the entire expression g(x).",
  },
  {
    type: "mc",
    question: "Let f(x) = √x and g(x) = x − 6. What is the domain of (f ∘ g)(x)? Use interval notation.",
    options: ["(−∞, 6]", "[6, ∞)", "(−∞, ∞)", "(6, ∞)"],
    correctIndex: 1,
    explanation: "The composite is f(g(x)) = √(x − 6). Its radicand is zero at x = 6 and is nonnegative for inputs to the right, including 6. Hence the domain is [6, ∞).",
    hint: "Build the composite first, then apply the square-root restriction.",
  },
  {
    type: "fill",
    question: "Let f(x) = x² + 1 and g(x) = 1/(x − 2). Write (g ∘ f)(x) in simplified form.",
    mathLines: ["(g ∘ f)(x) = g(f(x)) = g(x² + 1)"],
    answer: "1/(x^2-1)",
    accepted: ["1/(x²−1)", "1/(x^2-1)", "1 / (x² − 1)", "1 / (x^2 - 1)"],
    explanation: "Substitute f(x) = x² + 1 into g: g(f(x)) = 1/[(x² + 1) − 2] = 1/(x² − 1).",
    hint: "The output of f becomes the input expression in g.",
  },

  // 11. Inverse Portal — algebra and domain-range exchange
  {
    type: "mc",
    question: "What is the inverse of f(x) = 3x − 8?",
    options: ["f⁻¹(x) = 3x + 8", "f⁻¹(x) = (x + 8)/3", "f⁻¹(x) = (x − 8)/3", "f⁻¹(x) = 1/(3x − 8)"],
    correctIndex: 1,
    explanation: "Start with y = 3x − 8, interchange x and y, and solve: x = 3y − 8, so x + 8 = 3y and y = (x + 8)/3. Thus f⁻¹(x) = (x + 8)/3.",
    hint: "For an inverse, swap x and y before solving for y.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "Find the inverse rule of f(x) = (x − 5)/2.",
    mathLines: ["y = (x − 5)/2", "x = (y − 5)/2"],
    answer: "2x+5",
    accepted: ["2x+5", "2x + 5"],
    explanation: "After swapping variables, x = (y − 5)/2. Multiplying by 2 gives 2x = y − 5, so y = 2x + 5. Therefore f⁻¹(x) = 2x + 5.",
    hint: "Swap x and y, then isolate y.",
    visual: "inverse",
  },
  {
    type: "mc",
    question: "Let f(x) = x² with domain [0, ∞). What is f⁻¹(49)?",
    options: ["−7", "0", "7", "49"],
    correctIndex: 2,
    explanation: "Restricting f(x) = x² to [0, ∞) makes it one-to-one, with inverse f⁻¹(x) = √x. Hence f⁻¹(49) = √49 = 7.",
    hint: "The stated domain selects the principal, nonnegative square root.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "A one-to-one function f has domain [−2, 5) and range [1, ∞). What is the domain of f⁻¹? Use interval notation.",
    answer: "[1, ∞)",
    accepted: ["[1, ∞)", "[1,∞)", "[1, infinity)", "[1,infinity)"],
    explanation: "An inverse reverses inputs and outputs. Therefore the domain of f⁻¹ is the range of f, which is [1, ∞).",
    hint: "For inverse functions, the original range becomes the inverse domain.",
    visual: "inverse",
  },

  // 12. Quadratic Skyline — vertex, intercepts, and extrema
  {
    type: "mc",
    question: "What are the vertex and opening direction of y = 2(x − 3)² − 5?",
    options: [
      "Vertex (−3, −5), opens upward",
      "Vertex (3, −5), opens upward",
      "Vertex (3, 5), opens downward",
      "Vertex (−3, 5), opens downward",
    ],
    correctIndex: 1,
    explanation: "The equation is in vertex form y = a(x − h)² + k. Here h = 3 and k = −5, so the vertex is (3, −5). Since a = 2 is positive, the parabola opens upward.",
    hint: "Read h and k from x − h and +k; the sign of a determines the opening.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "Find the x-intercepts of y = x² − 5x + 6. List the x-values from least to greatest, separated by a comma.",
    mathLines: ["x² − 5x + 6 = 0"],
    answer: "2, 3",
    accepted: ["2, 3", "2,3"],
    explanation: "Factor x² − 5x + 6 as (x − 2)(x − 3). Setting each factor equal to zero gives x = 2 and x = 3, so the x-intercepts occur at those x-values.",
    hint: "Find two numbers whose product is 6 and whose sum is −5.",
    visual: "quadratic",
  },
  {
    type: "mc",
    question: "What is the y-intercept of y = −x² + 4x − 1?",
    options: ["−1", "0", "1", "4"],
    correctIndex: 0,
    explanation: "A y-intercept occurs where x = 0. Substitution gives y = −(0)² + 4(0) − 1 = −1, so the intercept is (0, −1) and its y-value is −1.",
    hint: "Set x equal to 0 to find a y-intercept.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "What is the absolute maximum value of y = −(x + 2)² + 7?",
    answer: "7",
    accepted: ["7"],
    explanation: "Because (x + 2)² is nonnegative, −(x + 2)² is never positive. The greatest possible value occurs when x = −2, making the squared term 0; then y = 7. Thus the absolute maximum value is 7.",
    hint: "The vertex gives the maximum when the squared term has a negative coefficient.",
    visual: "quadratic",
  },
];
