import type { Challenge } from "../activities";

export const functionScoutBank: Challenge[] = [
  {
    type: "mc",
    question: "Which statement correctly defines a function?",
    options: [
      "Each output is paired with exactly one input.",
      "Each input may be paired with any number of outputs.",
      "Each input is paired with exactly one output.",
      "No two inputs may be paired with the same output.",
    ],
    correctIndex: 2,
    explanation: "A function assigns exactly one output to each input. Different inputs are allowed to share an output, so neither uniqueness of outputs nor one-to-one matching is required.",
    hint: "Focus on what must happen to every input.",
  },
  {
    type: "fill",
    question: "Complete the statement: Different inputs may share an output, but one input cannot be paired with two different ___.",
    answer: "outputs",
    accepted: ["outputs", "output"],
    explanation: "A function gives each input one and only one output. Repeated outputs are allowed, but two different outputs for the same input violate the definition.",
    hint: "The restriction concerns what an input produces.",
  },
  {
    type: "mc",
    question: "Which relation is a function?",
    options: [
      "{(1, 4), (1, −4), (2, 0)}",
      "{(−3, 2), (0, −1), (4, 2), (6, 5)}",
      "{(5, 0), (−1, 3), (5, 6)}",
      "{(2, 7), (2, −7), (7, 2)}",
    ],
    correctIndex: 1,
    explanation: "In the second relation, the inputs −3, 0, 4, and 6 each occur once, so each has one output. The repeated output 2 is allowed. Every other option repeats an input with two different outputs.",
    hint: "Inspect the first coordinate in every ordered pair.",
  },
  {
    type: "fill",
    question: "Is R = {(−2, 5), (0, 1), (−2, −5)} a function? Enter \"function\" or \"not a function\".",
    answer: "not a function",
    accepted: ["not a function", "no", "false"],
    explanation: "R is not a function because the input −2 is paired with both 5 and −5. One input cannot have two different outputs in a function.",
    hint: "Look for a repeated first coordinate with different second coordinates.",
  },
  {
    type: "mc",
    question: "Which mapping represents a function?",
    options: [
      "1 → P and 1 → Q; 2 → R",
      "1 → P; 2 → P; 3 → R",
      "4 → M and 4 → N; 5 → N",
      "0 → S and 0 → T; 6 → S",
    ],
    correctIndex: 1,
    explanation: "The second mapping gives each input exactly one arrow. Inputs 1 and 2 may both map to P; many-to-one mappings are functions. In every other option, one input has arrows to two different outputs.",
    hint: "A valid mapping has one outgoing arrow from each input.",
  },
  {
    type: "fill",
    question: "Decide whether the displayed mapping is a function. Enter \"function\" or \"not a function\".",
    mathLines: ["−1 → 4", "0 → 2", "3 → 2", "5 → −6"],
    answer: "function",
    accepted: ["function", "yes", "true"],
    explanation: "This is a function because each input (−1, 0, 3, and 5) has exactly one arrow. The shared output 2 for inputs 0 and 3 is permitted.",
    hint: "Check the number of arrows leaving each input, not the number arriving at an output.",
  },
  {
    type: "mc",
    question: "A mapping has inputs A, B, and C. It includes arrows A → 1 and B → 2, but no arrow leaves C. What is the correct conclusion?",
    options: [
      "It is a function because A and B each have one output.",
      "It is a function because 1 and 2 are different outputs.",
      "It is not a function because C has no output.",
      "It is not a function because C should map to both 1 and 2.",
    ],
    correctIndex: 2,
    explanation: "A function must assign an output to every input in its stated domain. Since C has no outgoing arrow, C has no assigned output, so this mapping is not a function.",
    hint: "Every input needs exactly one arrow—not zero and not two.",
  },
  {
    type: "fill",
    question: "Does the table define y as a function of x? Enter \"function\" or \"not a function\".",
    mathLines: ["x:  −2    0    3    3", "y:   5   −1    4    6"],
    answer: "not a function",
    accepted: ["not a function", "no", "false"],
    explanation: "The input 3 appears twice, once with output 4 and once with output 6. Because one input gives two different outputs, the table does not define a function.",
    hint: "Compare the entries in the x-row before comparing the y-row.",
  },
  {
    type: "mc",
    question: "Which table defines y as a function of x?",
    options: [
      "x: 1, 1, 4; y: 2, 5, 7",
      "x: −2, 0, 3, 7; y: 4, 4, 1, 1",
      "x: 0, 2, 2, 5; y: −1, 8, 9, 3",
      "x: 1, 1, 1, 3; y: 0, 0, 2, 4",
    ],
    correctIndex: 1,
    explanation: "In the second table, every x-value occurs only once, so every input has one output. Its repeated outputs 4 and 1 are allowed. The other tables each give a repeated x-value two different y-values.",
    hint: "Repeated y-values are fine; repeated x-values with different y-values are not.",
  },
  {
    type: "fill",
    question: "A table already lists f(4) = −3. If the input 4 is listed again and the relation is still to be a function, what output must be listed?",
    answer: "-3",
    accepted: ["-3", "−3"],
    explanation: "For the input 4, a function can have only one output. Since f(4) = −3 is already given, a repeated listing for input 4 must also have output −3.",
    hint: "A repeated input may not receive a different output.",
  },
  {
    type: "mc",
    question: "Which equation defines y as a function of x?",
    options: [
      "x = y²",
      "y = 2x − 3",
      "x² + y² = 9",
      "y² = x + 1",
    ],
    correctIndex: 1,
    explanation: "The equation y = 2x − 3 assigns one y-value to every chosen x-value. The other equations can give two y-values for one x-value; for example, x = 4 in x = y² gives y = 2 and y = −2.",
    hint: "Ask whether solving for y can produce two different values for one x-value.",
  },
  {
    type: "fill",
    question: "Does y² = 4x + 4 define y as a function of x? Enter \"function\" or \"not a function\".",
    answer: "not a function",
    accepted: ["not a function", "no", "false"],
    explanation: "When x = 0, the equation becomes y² = 4, so y = 2 or y = −2. Since the single input 0 produces two outputs, the relation is not a function of x.",
    hint: "Test one x-value that makes the right side positive, then solve for y.",
  },
  {
    type: "mc",
    question: "Does the equation x = (y − 1)³ define y as a function of x?",
    mathLines: ["x = (y − 1)³", "y = ∛x + 1"],
    options: [
      "Yes; each x-value gives the single output y = ∛x + 1.",
      "Yes; a relation is a function whenever x is written alone.",
      "No; a cubic expression always gives two y-values for one x-value.",
      "No; y must be squared for a relation to be a function.",
    ],
    correctIndex: 0,
    explanation: "Taking the cube root gives y = ∛x + 1. Every real x has exactly one real cube root, so this equation assigns exactly one y-value to each x-value.",
    hint: "Isolate y and recall how many real cube roots a real number has.",
  },
  {
    type: "fill",
    question: "Does 3y − 6 = x² define y as a function of x? Enter \"function\" or \"not a function\".",
    mathLines: ["3y − 6 = x²", "3y = x² + 6", "y = (x² + 6)/3"],
    answer: "function",
    accepted: ["function", "yes", "true"],
    explanation: "Solving for y gives y = (x² + 6)/3. For every x-value, x² has one value, so the formula produces exactly one y-value. Therefore it defines a function of x.",
    hint: "Solve the equation for y, then check whether the result is single-valued.",
  },
  {
    type: "mc",
    question: "Which statement gives the vertical line test for a graph representing y as a function of x?",
    options: [
      "Every horizontal line intersects the graph at most once.",
      "At least one vertical line intersects the graph exactly once.",
      "Every vertical line intersects the graph at most once.",
      "Every vertical line intersects the graph at least twice.",
    ],
    correctIndex: 2,
    explanation: "A vertical line fixes one x-value. If every vertical line meets the graph at most once, no x-value is paired with two y-values, which is exactly the definition of a function of x.",
    hint: "A vertical line keeps x fixed while checking possible y-values.",
  },
  {
    type: "fill",
    question: "A graph contains both (2, −1) and (2, 5). Is it the graph of a function of x? Enter \"function\" or \"not a function\".",
    answer: "not a function",
    accepted: ["not a function", "no", "false"],
    explanation: "The vertical line x = 2 contains both points, so it intersects the graph twice. Equivalently, the input 2 has outputs −1 and 5; therefore the graph is not a function of x.",
    hint: "The two points have the same x-coordinate.",
  },
  {
    type: "mc",
    question: "Which precise graph description guarantees that a relation is a function of x?",
    options: [
      "Every horizontal line intersects the graph at most once.",
      "The vertical line x = 0 intersects the graph exactly once.",
      "Every vertical line intersects the graph at most once.",
      "The vertical line x = 1 intersects the graph twice.",
    ],
    correctIndex: 2,
    explanation: "Only the condition that every vertical line intersects at most once checks all possible x-values and guarantees one y-value per x-value. A horizontal-line condition concerns one-to-one behavior instead.",
    hint: "The function test must work for all vertical lines, not just one selected line.",
  },
  {
    type: "fill",
    question: "Does the displayed piecewise rule define a function? Enter \"function\" or \"not a function\".",
    piecewise: {
      label: "p(x) =",
      cases: [
        { expression: "3x − 1", condition: "x ≤ 2" },
        { expression: "x + 5", condition: "x ≥ 2" },
      ],
    },
    answer: "not a function",
    accepted: ["not a function", "no", "false"],
    explanation: "At x = 2, both conditions apply. The first rule gives 3(2) − 1 = 5, while the second gives 2 + 5 = 7. Because x = 2 receives two different outputs, p is not a function.",
    hint: "Check whether an input belongs to more than one condition.",
  },
  {
    type: "mc",
    question: "Why does the displayed piecewise definition represent a function?",
    piecewise: {
      label: "f(x) =",
      cases: [
        { expression: "−x", condition: "x < 0" },
        { expression: "x² + 1", condition: "x ≥ 0" },
      ],
    },
    options: [
      "Every x-value satisfies exactly one condition, and each rule gives one output.",
      "Both rules are applied to every x-value, so two outputs are guaranteed.",
      "The outputs from the two rules can never be equal.",
      "It passes the horizontal line test, so it must be a function.",
    ],
    correctIndex: 0,
    explanation: "The conditions x < 0 and x ≥ 0 do not overlap and together include every real x-value. Thus exactly one rule applies to each input, and that rule supplies one output.",
    hint: "Check whether the conditions divide the inputs without overlap.",
  },
  {
    type: "fill",
    question: "Let q be a function with q(−4) = 7. What ordered pair must lie on the graph of q?",
    answer: "(-4, 7)",
    accepted: ["(-4, 7)", "(-4,7)", "(−4, 7)", "(−4,7)"],
    explanation: "Function notation q(−4) = 7 says that input −4 has output 7. A graph records an input and its output as the ordered pair (−4, 7).",
    hint: "Write an ordered pair as (input, output).",
  },
];
