import type { Challenge } from "../activities";

export const intervalObservatoryBank: Challenge[] = [
  {
    type: "fill",
    question: "Find the domain of f(x) = √(7 − 2x). Report your answer in interval notation.",
    mathLines: ["7 − 2x ≥ 0", "−2x ≥ −7", "x ≤ 7/2"],
    answer: "(−∞, 7/2]",
    accepted: ["(−∞, 7/2]", "(-infinity, 7/2]", "(−∞,3.5]", "(-infinity,3.5]"],
    explanation: "For a real square root, the radicand must be nonnegative. Solving 7 − 2x ≥ 0 gives x ≤ 7/2. The endpoint 7/2 is included because it makes the radicand 0, so the domain is (−∞, 7/2].",
    hint: "Set the expression inside the square root greater than or equal to 0, then reverse the inequality when dividing by −2.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "What is the domain of g(x) = (x + 4)/(x² − 9)? Report the domain in interval notation.",
    options: ["(−∞, −3) ∪ (−3, 3) ∪ (3, ∞)", "(−∞, −3] ∪ [−3, 3] ∪ [3, ∞)", "(−∞, 3) ∪ (3, ∞)", "(−∞, −3) ∪ (−3, ∞)"],
    correctIndex: 0,
    explanation: "A rational expression is undefined when its denominator is 0. Since x² − 9 = (x − 3)(x + 3), x = −3 and x = 3 must both be excluded. Therefore the domain is (−∞, −3) ∪ (−3, 3) ∪ (3, ∞).",
    hint: "Factor the denominator and exclude every zero of it.",
    visual: "domain",
  },
  {
    type: "fill",
    question: "Find the range of h(x) = 2 − (x + 1)². Report your answer in interval notation.",
    mathLines: ["(x + 1)² ≥ 0", "−(x + 1)² ≤ 0", "2 − (x + 1)² ≤ 2"],
    answer: "(−∞, 2]",
    accepted: ["(−∞, 2]", "(-infinity, 2]"],
    explanation: "A square is never negative, so −(x + 1)² is never positive. Thus h(x) cannot exceed 2. At x = −1, the squared term is 0 and h(−1) = 2, so 2 is included. The range is (−∞, 2].",
    hint: "Identify the vertex and whether the parabola opens upward or downward.",
    visual: "quadratic",
  },
  {
    type: "mc",
    question: "What is the range of r(x) = √(x − 5) − 3? Report the range in interval notation.",
    options: ["[−3, ∞)", "(−3, ∞)", "[5, ∞)", "(−∞, −3]"],
    correctIndex: 0,
    explanation: "The principal square root √(x − 5) is at least 0. Subtracting 3 makes every output at least −3. When x = 5, r(5) = −3, so the endpoint is included. The range is [−3, ∞).",
    hint: "Start with the possible outputs of a square root, then apply the vertical shift.",
    visual: "domain",
  },
  {
    type: "fill",
    question: "Find the domain of p(x) = ∛(x − 6). Report your answer in interval notation.",
    answer: "(−∞, ∞)",
    accepted: ["(−∞, ∞)", "(-infinity, infinity)"],
    explanation: "Unlike an even root, a cube root is defined for negative, zero, and positive radicands. Because x − 6 can be any real number, p(x) is defined for every real x. Its domain is (−∞, ∞).",
    hint: "Odd roots can take negative numbers as inputs.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "What is the domain of q(x) = √((x − 1)/(x + 2))? Report the domain in interval notation.",
    options: ["(−∞, −2) ∪ [1, ∞)", "(−∞, −2] ∪ [1, ∞)", "[−2, 1]", "(−2, 1)"],
    correctIndex: 0,
    explanation: "The radicand must be nonnegative and x + 2 cannot be 0. A sign check around the critical values −2 and 1 shows (x − 1)/(x + 2) is nonnegative on (−∞, −2) and [1, ∞). The value −2 is excluded because it makes the denominator 0; the value 1 is included because it makes the radicand 0.",
    hint: "Mark where the numerator or denominator is 0, then test the sign on each resulting interval.",
    visual: "domain",
  },
  {
    type: "fill",
    question: "Find the range of s(x) = 3/(x − 2) + 1. Report your answer in interval notation.",
    answer: "(−∞, 1) ∪ (1, ∞)",
    accepted: ["(−∞, 1) ∪ (1, ∞)", "(-infinity, 1) U (1, infinity)", "(-infinity,1)U(1,infinity)", "(−∞,1)∪(1,∞)"],
    explanation: "The fraction 3/(x − 2) can never equal 0, so adding 1 can never produce the output 1. Conversely, for every y other than 1, the equation y = 3/(x − 2) + 1 can be solved for x. Therefore the range is (−∞, 1) ∪ (1, ∞).",
    hint: "A reciprocal graph shifted up by 1 has a horizontal asymptote at y = 1, which it never reaches.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "A graph consists exactly of a horizontal segment from the filled point (−4, 2) to the open point (1, 2). What is its domain in interval notation?",
    options: ["[−4, 1)", "(−4, 1]", "[−4, 1]", "(−4, 1)"],
    correctIndex: 0,
    explanation: "The domain is the set of x-coordinates on the segment. The filled point at x = −4 is included, while the open point at x = 1 is excluded. Hence the domain is [−4, 1).",
    hint: "Read x-values from left to right; filled endpoints use brackets and open endpoints use parentheses.",
    visual: "domain",
  },
  {
    type: "fill",
    question: "A graph consists exactly of the line segment from the open point (−2, −5) to the filled point (3, 1). Find its range in interval notation.",
    answer: "(−5, 1]",
    accepted: ["(−5, 1]"],
    explanation: "The range is made from the y-coordinates on the segment. It includes every y-value between −5 and 1. The open point excludes −5, and the filled point includes 1, so the range is (−5, 1].",
    hint: "For range, scan the graph from bottom to top and use the endpoint markers.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "A graph has exactly two pieces: a closed segment from (−5, 2) to (−1, 2), and a ray that begins at the open point (2, −1) and extends right forever. What is its domain in interval notation?",
    options: ["[−5, −1] ∪ (2, ∞)", "(−5, −1) ∪ [2, ∞)", "[−5, 2) ∪ (2, ∞)", "[−5, −1] ∪ [2, ∞)"],
    correctIndex: 0,
    explanation: "The closed segment contributes all x-values from −5 through −1, including both endpoints. The rightward ray contributes x-values greater than 2 but excludes 2 because its starting point is open. Thus the domain is [−5, −1] ∪ (2, ∞).",
    hint: "Find the x-values covered by each piece, then join the two intervals with ∪.",
    visual: "domain",
  },
  {
    type: "fill",
    question: "Find the domain of the piecewise function. Report your answer in interval notation.",
    piecewise: {
      label: "f(x) =",
      cases: [
        { expression: "√(x + 1)", condition: "x < 2" },
        { expression: "1/(x − 3)", condition: "x ≥ 2" },
      ],
    },
    answer: "[−1, 3) ∪ (3, ∞)",
    accepted: ["[−1, 3) ∪ (3, ∞)", "[-1, 3) U (3, infinity)", "[-1,3)U(3,infinity)", "[−1,3)∪(3,∞)"],
    explanation: "On the branch x < 2, √(x + 1) requires x ≥ −1, giving [−1, 2). On the branch x ≥ 2, 1/(x − 3) is defined except at x = 3, giving [2, 3) ∪ (3, ∞). Combining the branches gives [−1, 3) ∪ (3, ∞).",
    hint: "Apply each branch condition first, then enforce any restriction created by its formula.",
    visual: "piecewise",
  },
  {
    type: "mc",
    question: "What is the range of the piecewise function? Report the range in interval notation.",
    piecewise: {
      label: "g(x) =",
      cases: [
        { expression: "x²", condition: "x < 0" },
        { expression: "x + 1", condition: "x ≥ 0" },
      ],
    },
    options: ["(0, ∞)", "[0, ∞)", "[1, ∞)", "(−∞, ∞)"],
    correctIndex: 0,
    explanation: "For x < 0, x² produces every positive output but never 0, so that branch has range (0, ∞). For x ≥ 0, x + 1 has range [1, ∞), which is already contained in (0, ∞). The combined range is (0, ∞).",
    hint: "Determine the outputs of each branch over its stated input condition, not over all real inputs.",
    visual: "piecewise",
  },
  {
    type: "fill",
    question: "Find the domain of m(x) = √(4 − x²). Report your answer in interval notation.",
    mathLines: ["4 − x² ≥ 0", "x² ≤ 4", "−2 ≤ x ≤ 2"],
    answer: "[−2, 2]",
    accepted: ["[−2, 2]", "[-2, 2]"],
    explanation: "The radicand must be nonnegative. The inequality 4 − x² ≥ 0 is equivalent to x² ≤ 4, so x lies from −2 to 2. Both endpoints make the radicand 0 and are allowed. Therefore the domain is [−2, 2].",
    hint: "Require the radicand to be at least 0, then solve the resulting quadratic inequality.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "What is the domain of n(x) = 1/√(x − 6)? Report the domain in interval notation.",
    options: ["(6, ∞)", "[6, ∞)", "(−∞, 6)", "(−∞, 6]"],
    correctIndex: 0,
    explanation: "Because √(x − 6) is in the denominator, it must be positive: it cannot be negative and it cannot be 0. Thus x − 6 > 0, so the domain is (6, ∞).",
    hint: "A square root in a denominator must be strictly greater than 0.",
    visual: "domain",
  },
  {
    type: "fill",
    question: "Find the range of a(x) = |x − 3| + 2. Report your answer in interval notation.",
    answer: "[2, ∞)",
    accepted: ["[2, ∞)", "[2, infinity)"],
    explanation: "An absolute value is always at least 0. Therefore |x − 3| + 2 is at least 2. At x = 3, the absolute-value expression is 0, so a(3) = 2 and the minimum is included. The range is [2, ∞).",
    hint: "Locate the minimum possible value of the absolute-value term before applying the vertical shift.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "What is the range of b(x) = x/(x + 1)? Report the range in interval notation.",
    options: ["(−∞, 1) ∪ (1, ∞)", "(−∞, 0) ∪ (0, ∞)", "(−∞, 1]", "(−∞, ∞)"],
    correctIndex: 0,
    explanation: "Rewrite b(x) as 1 − 1/(x + 1). The reciprocal term can never be 0, so b(x) can never equal 1. Every other real output is attainable, so the range is (−∞, 1) ∪ (1, ∞).",
    hint: "Divide or rewrite the expression to identify the horizontal value the graph cannot reach.",
    visual: "domain",
  },
  {
    type: "fill",
    question: "Find the domain of c(x) = √(x² − 4)/(x − 1). Report your answer in interval notation.",
    mathLines: ["x² − 4 ≥ 0", "(x − 2)(x + 2) ≥ 0", "x ≤ −2 or x ≥ 2"],
    answer: "(−∞, −2] ∪ [2, ∞)",
    accepted: ["(−∞, −2] ∪ [2, ∞)", "(-infinity, -2] U [2, infinity)", "(-infinity,-2]U[2,infinity)", "(−∞,−2]∪[2,∞)"],
    explanation: "The square-root radicand requires x² − 4 ≥ 0, which holds for x ≤ −2 or x ≥ 2. The denominator would exclude x = 1, but 1 is already outside those intervals. Hence the domain is (−∞, −2] ∪ [2, ∞).",
    hint: "First solve the radical restriction; then check whether the denominator removes any value that remains.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "What is the range of d(x) = (x − 2)² − 4? Report the range in interval notation.",
    options: ["[−4, ∞)", "(−4, ∞)", "(−∞, −4]", "(−∞, ∞)"],
    correctIndex: 0,
    explanation: "The square (x − 2)² is at least 0, so d(x) is at least −4. At x = 2, d(2) = −4, so the minimum is reached. Since the parabola opens upward, all larger y-values occur. The range is [−4, ∞).",
    hint: "Use the vertex of the upward-opening parabola.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "Find the range of e(x) = √(9 − x²). Report your answer in interval notation.",
    mathLines: ["9 − x² ≥ 0, so −3 ≤ x ≤ 3", "0 ≤ √(9 − x²) ≤ 3"],
    answer: "[0, 3]",
    accepted: ["[0, 3]"],
    explanation: "On its allowed inputs from −3 to 3, the radicand 9 − x² ranges from 0 to 9. Taking the principal square root gives outputs from 0 to 3. Both occur: e(−3) = e(3) = 0 and e(0) = 3. Therefore the range is [0, 3].",
    hint: "Find the smallest and largest possible values of the radicand on its domain, then take square roots.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "What is the domain of k(x) = 1/√(5 − x)? Report the domain in interval notation.",
    options: ["(−∞, 5)", "(−∞, 5]", "[5, ∞)", "(5, ∞)"],
    correctIndex: 0,
    explanation: "The radicand 5 − x must be positive because its square root is in the denominator. Solving 5 − x > 0 gives x < 5. The endpoint 5 is excluded because it would make the denominator 0. The domain is (−∞, 5).",
    hint: "Combine the radical rule with the fact that a denominator cannot equal 0.",
    visual: "domain",
  },
];
