import type { Challenge } from "../activities";

export const inversePortalBank: Challenge[] = [
  {
    type: "mc",
    question: "A table defines a function f. Which table proves that f is one-to-one?",
    options: [
      "x: −2, 0, 2;  f(x): 1, 3, 5",
      "x: −2, 0, 2;  f(x): 1, 3, 3",
      "x: −2, 0, 2;  f(x): 4, 4, 4",
      "x: −2, 0, 2;  f(x): −1, 2, −1",
    ],
    correctIndex: 0,
    explanation: "A function is one-to-one exactly when distinct inputs have distinct outputs. In the first table, the outputs 1, 3, and 5 are all different, so no horizontal line can meet its graph twice. Each other table repeats an output.",
    hint: "Check whether any two different x-values share the same output.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "Find f⁻¹(x) if f(x) = 4x − 9.",
    mathLines: ["y = 4x − 9", "x = 4y − 9", "y = (x + 9)/4"],
    answer: "(x+9)/4",
    accepted: ["(x+9)/4", "(x + 9)/4", "(x+9)÷4", "(x + 9) ÷ 4"],
    explanation: "Start with y = 4x − 9, interchange x and y, and solve: x = 4y − 9 gives x + 9 = 4y, so y = (x + 9)/4. A check gives f((x + 9)/4) = 4((x + 9)/4) − 9 = x, proving the inverse rule.",
    hint: "Swap x and y first, then isolate y.",
    visual: "inverse",
  },
  {
    type: "mc",
    question: "If (−3, 8) lies on the graph of a one-to-one function g, which point lies on the graph of g⁻¹?",
    options: ["(−3, 8)", "(8, −3)", "(3, −8)", "(−8, 3)"],
    correctIndex: 1,
    explanation: "An inverse reverses each input-output pair. Since g(−3) = 8, the inverse satisfies g⁻¹(8) = −3; therefore (8, −3) lies on the inverse graph.",
    hint: "For an inverse, exchange the coordinates of every point.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "Find h⁻¹(x) if h(x) = (3x − 5)/2.",
    mathLines: ["y = (3x − 5)/2", "2x = 3y − 5", "y = (2x + 5)/3"],
    answer: "(2x+5)/3",
    accepted: ["(2x+5)/3", "(2x + 5)/3", "(2x+5)÷3", "(2x + 5) ÷ 3"],
    explanation: "After interchanging x and y, x = (3y − 5)/2. Multiplying by 2 gives 2x = 3y − 5, so 3y = 2x + 5 and h⁻¹(x) = (2x + 5)/3. Substitution into h returns x, so the rule is correct.",
    hint: "After swapping x and y, clear the denominator before solving for y.",
    visual: "inverse",
  },
  {
    type: "mc",
    question: "For f(x) = √(x + 1), the domain of f is [−1, ∞) and the range of f is [0, ∞). What is the domain of f⁻¹?",
    options: ["[−1, ∞)", "[0, ∞)", "(−∞, −1]", "(−∞, 0]"],
    correctIndex: 1,
    explanation: "The domain of an inverse equals the range of the original function. Because the range of f is [0, ∞), the domain of f⁻¹ is [0, ∞).",
    hint: "An inverse swaps inputs and outputs.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "A one-to-one function p has domain (−∞, 4] and range [−3, ∞). State the range of p⁻¹ in interval notation.",
    answer: "(-infinity,4]",
    accepted: ["(−∞, 4]", "(-∞, 4]", "(-infinity,4]", "(-infinity, 4]"],
    explanation: "Inverse functions interchange domain and range. Since the domain of p is (−∞, 4], the range of p⁻¹ is (−∞, 4].",
    hint: "The inverse's range comes from the original function's domain.",
    visual: "inverse",
  },
  {
    type: "mc",
    question: "If f is one-to-one, which transformation of the graph of f produces the graph of f⁻¹?",
    options: [
      "Reflect it across the x-axis.",
      "Reflect it across the y-axis.",
      "Reflect it across the line y = x.",
      "Translate it 1 unit up and 1 unit right.",
    ],
    correctIndex: 2,
    explanation: "Every point (a, b) on f becomes (b, a) on f⁻¹. Reflection across y = x exchanges the two coordinates, so that reflection produces the inverse graph.",
    hint: "Which line is unchanged when x- and y-coordinates are exchanged?",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "Let g(x) = 3x − 7. Find g⁻¹(11).",
    mathLines: ["g(x) = 11", "3x − 7 = 11", "x = 6"],
    answer: "6",
    accepted: ["6"],
    explanation: "g⁻¹(11) asks for the input that g sends to 11. Solve 3x − 7 = 11: 3x = 18, so x = 6. Indeed, g(6) = 11, confirming g⁻¹(11) = 6.",
    hint: "Find the input whose output under g is 11.",
    visual: "inverse",
  },
  {
    type: "mc",
    question: "The function q(x) = x² is restricted to the domain [0, ∞). Which formula is q⁻¹(x)?",
    options: ["x²", "−√x", "√x", "±√x"],
    correctIndex: 2,
    explanation: "On [0, ∞), q is one-to-one. If y = x² with x ≥ 0, then x = √y, so q⁻¹(x) = √x. The negative root is excluded by the original restriction, and ±√x is not a single-valued function.",
    hint: "The restricted original inputs are nonnegative, so choose the matching square-root branch.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "Find r⁻¹(x) if r(x) = (x − 2)³ + 5.",
    mathLines: ["y = (x − 2)³ + 5", "x = (y − 2)³ + 5", "y = ∛(x − 5) + 2"],
    answer: "∛(x−5)+2",
    accepted: ["∛(x−5)+2", "∛(x − 5) + 2", "cuberoot(x-5)+2", "cuberoot(x − 5) + 2"],
    explanation: "Swap x and y, then undo the operations in reverse order: x − 5 = (y − 2)³, so ∛(x − 5) = y − 2 and y = ∛(x − 5) + 2. Cubing after subtracting 2 recovers x − 5, which verifies the inverse.",
    hint: "After the swap, subtract 5 and then take a cube root.",
    visual: "inverse",
  },
  {
    type: "mc",
    question: "Which function fails the horizontal line test and therefore does not have an inverse function on its full domain?",
    options: ["a(x) = x³", "b(x) = |x|", "c(x) = 2x − 3", "d(x) = 1/(x − 4)"],
    correctIndex: 1,
    explanation: "For b(x) = |x|, inputs such as −2 and 2 both produce 2. Thus the horizontal line y = 2 intersects the graph twice, so b is not one-to-one and its inverse relation would not be a function without a domain restriction.",
    hint: "Look for two different inputs that yield the same output.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "The relation s contains the ordered pairs {(−2, 1), (0, 5), (3, 7)}. Write the inverse relation by listing its ordered pairs.",
    answer: "{(1,-2),(5,0),(7,3)}",
    accepted: ["{(1,-2),(5,0),(7,3)}", "{(1, −2), (5, 0), (7, 3)}", "(1,-2),(5,0),(7,3)", "(1, −2), (5, 0), (7, 3)"],
    explanation: "Form the inverse relation by reversing every ordered pair: (−2, 1) becomes (1, −2), (0, 5) becomes (5, 0), and (3, 7) becomes (7, 3).",
    hint: "Exchange the first and second coordinate in each pair.",
    visual: "inverse",
  },
  {
    type: "mc",
    question: "A one-to-one function k has domain [−4, ∞) and range (−∞, 6]. Which domain-and-range pair belongs to k⁻¹?",
    options: [
      "Domain [−4, ∞), range (−∞, 6]",
      "Domain (−∞, 6], range (−∞, 6]",
      "Domain [−4, ∞), range [−4, ∞)",
      "Domain (−∞, 6], range [−4, ∞)",
    ],
    correctIndex: 3,
    explanation: "An inverse interchanges inputs and outputs. Therefore the domain of k⁻¹ is k's range, (−∞, 6], and the range of k⁻¹ is k's domain, [−4, ∞).",
    hint: "Write the original range first; it becomes the inverse domain.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "The one-to-one function below is defined piecewise. Find f⁻¹(x). Give the two inverse rules with their conditions.",
    piecewise: {
      label: "f(x) =",
      cases: [
        { expression: "x + 2", condition: "x < 0" },
        { expression: "2x + 2", condition: "x ≥ 0" },
      ],
    },
    answer: "x-2 if x<2; (x-2)/2 if x≥2",
    accepted: [
      "x-2 if x<2; (x-2)/2 if x≥2",
      "x − 2 if x < 2; (x − 2)/2 if x ≥ 2",
      "x-2, x<2; (x-2)/2, x≥2",
      "x − 2, x < 2; (x − 2)/2, x ≥ 2",
    ],
    explanation: "For the first branch, y = x + 2 with x < 0 has outputs below 2, so its inverse rule is x − 2 for x < 2. For the second branch, y = 2x + 2 with x ≥ 0 has outputs at least 2, so its inverse is (x − 2)/2 for x ≥ 2. The two output sets meet without overlapping, so the inverse is a function.",
    hint: "Solve each branch for its input, then use that branch's outputs as the inverse condition.",
    visual: "inverse",
  },
  {
    type: "mc",
    question: "For m(x) = (x + 4)/(x − 1), which rule is m⁻¹(x)?",
    options: ["(x − 4)/(x + 1)", "(x + 4)/(x − 1)", "(x − 1)/(x + 4)", "(4 − x)/(x − 1)"],
    correctIndex: 1,
    explanation: "Set y = (x + 4)/(x − 1) and interchange variables: x = (y + 4)/(y − 1). Then x(y − 1) = y + 4, so xy − y = x + 4, y(x − 1) = x + 4, and y = (x + 4)/(x − 1). Thus m is its own inverse.",
    hint: "Swap x and y, cross-multiply, and collect the y-terms.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "A one-to-one function u has range (2, ∞). State the domain of u⁻¹ in interval notation.",
    answer: "(2,infinity)",
    accepted: ["(2, ∞)", "(2,∞)", "(2,infinity)", "(2, infinity)"],
    explanation: "The domain of an inverse is the range of the original function. Since the range of u is (2, ∞), the domain of u⁻¹ is (2, ∞).",
    hint: "The outputs of u become the permitted inputs of u⁻¹.",
    visual: "inverse",
  },
  {
    type: "mc",
    question: "A function v passes the horizontal line test. What conclusion follows?",
    options: [
      "v has a y-intercept of 0.",
      "v is one-to-one, so v⁻¹ is a function.",
      "v has domain (−∞, ∞).",
      "v is an even function.",
    ],
    correctIndex: 1,
    explanation: "Passing the horizontal line test means every output is paired with at most one input. That is exactly the definition of one-to-one, so reversing the pairs creates an inverse that is also a function.",
    hint: "The horizontal line test is the graph test for one-to-one.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "Find w⁻¹(x) if w(x) = eˣ − 3.",
    mathLines: ["y = eˣ − 3", "x = eʸ − 3", "y = ln(x + 3)"],
    answer: "ln(x+3)",
    accepted: ["ln(x+3)", "ln(x + 3)", "ln(x+3)"],
    explanation: "After swapping x and y, x + 3 = eʸ. Taking the natural logarithm of both sides gives y = ln(x + 3). Substituting it into w gives e^(ln(x + 3)) − 3 = x, which proves the rule.",
    hint: "After swapping, isolate the exponential expression and use the natural logarithm.",
    visual: "inverse",
  },
  {
    type: "mc",
    question: "Consider the piecewise function shown below. Which fact proves it is one-to-one?",
    piecewise: {
      label: "t(x) =",
      cases: [
        { expression: "x + 4", condition: "x < 0" },
        { expression: "2x + 4", condition: "x ≥ 0" },
      ],
    },
    options: [
      "Both pieces have positive slopes, and their output sets do not overlap.",
      "Both pieces contain the number 4 in their formulas.",
      "The first piece has negative inputs and the second piece has nonnegative inputs.",
      "The function has two different formulas.",
    ],
    correctIndex: 0,
    explanation: "Each rule is increasing on its own input set. The first branch produces only values below 4, while the second produces values at least 4, so no output is repeated between branches. Hence distinct inputs cannot share an output, proving t is one-to-one.",
    hint: "Check both whether each branch repeats an output and whether the branches can share an output.",
    visual: "inverse",
  },
  {
    type: "fill",
    question: "Let f(x) = 5x + 1 and g(x) = (x − 1)/5. Compute f(g(x)) and g(f(x)), in that order, to verify that g = f⁻¹.",
    mathLines: ["f(g(x)) = 5((x − 1)/5) + 1", "g(f(x)) = ((5x + 1) − 1)/5"],
    answer: "x; x",
    accepted: ["x; x", "x,x", "x, x", "x and x"],
    explanation: "f(g(x)) = 5((x − 1)/5) + 1 = x − 1 + 1 = x. Also, g(f(x)) = ((5x + 1) − 1)/5 = 5x/5 = x. Since both compositions equal x, g undoes f and therefore g = f⁻¹.",
    hint: "Substitute one rule into the other and simplify each composition.",
    visual: "inverse",
  },
];
