import type { Challenge } from "../activities";

export const operationForgeBank: Challenge[] = [
  {
    type: "mc",
    question: "Let f(x) = √(x + 2) and g(x) = 1/(x − 3). What is the domain of (f + g)(x)? Use interval notation.",
    mathLines: ["f(x) = √(x + 2)", "g(x) = 1/(x − 3)"],
    options: [
      "[−2, 3) ∪ (3, ∞)",
      "[−2, ∞)",
      "(−∞, 3) ∪ (3, ∞)",
      "[−2, 3]",
    ],
    correctIndex: 0,
    explanation: "For √(x + 2), require x + 2 ≥ 0, so x ≥ −2. For 1/(x − 3), x cannot equal 3. The sum is defined where both functions are defined: [−2, 3) ∪ (3, ∞).",
    hint: "Intersect the domains of the two original functions; a denominator cannot be zero.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f(x) = √(5 − x) and g(x) = ln(x + 1). Find the domain of (f − g)(x) in interval notation.",
    mathLines: ["f(x) = √(5 − x)", "g(x) = ln(x + 1)"],
    answer: "(−1, 5]",
    accepted: ["(−1, 5]", "(-1, 5]", "(−1,5]", "(-1,5]"],
    explanation: "The radical requires 5 − x ≥ 0, so x ≤ 5. The logarithm requires x + 1 > 0, so x > −1. Both requirements hold exactly on (−1, 5].",
    hint: "A square-root radicand must be nonnegative, while a logarithm's argument must be positive.",
    visual: "operations",
  },
  {
    type: "mc",
    question: "Let f(x) = (x + 1)/(x − 2) and g(x) = √(x − 4). What is the domain of (fg)(x)? Use interval notation.",
    mathLines: ["f(x) = (x + 1)/(x − 2)", "g(x) = √(x − 4)"],
    options: ["(4, ∞)", "(−∞, 2) ∪ (2, ∞)", "[4, ∞)", "[2, ∞)"],
    correctIndex: 2,
    explanation: "The rational function excludes x = 2. The square root requires x − 4 ≥ 0, or x ≥ 4. Every x ≥ 4 is already different from 2, so the product has domain [4, ∞).",
    hint: "A product is defined only where both factors are defined.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f(x) = √(x + 3) and g(x) = x − 1. Find the domain of (f/g)(x) in interval notation.",
    mathLines: ["(f/g)(x) = √(x + 3)/(x − 1)"],
    answer: "[−3, 1) ∪ (1, ∞)",
    accepted: ["[−3, 1) ∪ (1, ∞)", "[-3, 1) ∪ (1, ∞)", "[−3,1)∪(1,∞)", "[-3,1)U(1,infinity)"],
    explanation: "The numerator √(x + 3) requires x ≥ −3. Because g(x) is the divisor, x − 1 cannot be zero, so x ≠ 1. Thus the quotient is defined on [−3, 1) ∪ (1, ∞).",
    hint: "Keep the radical restriction and also exclude any input that makes the divisor zero.",
    visual: "operations",
  },
  {
    type: "mc",
    question: "Let f(x) = x² − 9 and g(x) = x − 3. What is the domain of (f/g)(x)? Use interval notation.",
    mathLines: ["(f/g)(x) = (x² − 9)/(x − 3) = ((x − 3)(x + 3))/(x − 3)"],
    options: ["(−∞, ∞)", "(−∞, 3) ∪ (3, ∞)", "[−3, ∞)", "(−∞, −3) ∪ (−3, ∞)"],
    correctIndex: 1,
    explanation: "Although (x − 3) cancels algebraically and the expression simplifies to x + 3, the original quotient has a zero denominator at x = 3. Therefore its domain is (−∞, 3) ∪ (3, ∞).",
    hint: "Find denominator restrictions before cancelling factors.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f(x) = ln(x − 2) and g(x) = √(7 − x). Find the domain of (f + g)(x) in interval notation.",
    mathLines: ["f(x) = ln(x − 2)", "g(x) = √(7 − x)"],
    answer: "(2, 7]",
    accepted: ["(2, 7]", "(2,7]"],
    explanation: "For ln(x − 2), require x − 2 > 0, so x > 2. For √(7 − x), require 7 − x ≥ 0, so x ≤ 7. Their common domain is (2, 7].",
    hint: "Find where each function is defined, then retain only their overlap.",
    visual: "operations",
  },
  {
    type: "mc",
    question: "Let f(x) = 1/(x + 4) and g(x) = √(x + 1). What is the domain of (fg)(x)? Use interval notation.",
    mathLines: ["f(x) = 1/(x + 4)", "g(x) = √(x + 1)"],
    options: [
      "(−∞, −4) ∪ (−4, ∞)",
      "(−∞, −4) ∪ [−1, ∞)",
      "(−1, ∞)",
      "[−1, ∞)",
    ],
    correctIndex: 3,
    explanation: "The radical requires x ≥ −1. The rational factor excludes x = −4, but −4 is not in [−1, ∞) anyway. Thus the overlap, and therefore the product domain, is [−1, ∞).",
    hint: "Check whether the excluded denominator value actually lies in the radical's allowable interval.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f be defined below and let g(x) = 1/(x + 2). Find the domain of (f + g)(x) in interval notation.",
    piecewise: {
      label: "f(x) =",
      cases: [
        { expression: "x + 1", condition: "x < 0" },
        { expression: "√x", condition: "x ≥ 0" },
      ],
    },
    answer: "(−∞, −2) ∪ (−2, ∞)",
    accepted: ["(−∞, −2) ∪ (−2, ∞)", "(-∞, -2) ∪ (-2, ∞)", "(−∞,−2)∪(−2,∞)", "(-infinity,-2)U(-2,infinity)"],
    explanation: "The first piece of f is defined for x < 0, and √x is defined for x ≥ 0, so f is defined for every real x. The function g is undefined only when x + 2 = 0, or x = −2. The sum therefore has domain (−∞, −2) ∪ (−2, ∞).",
    hint: "First combine the domains of the two pieces of f, then intersect with the domain of g.",
    visual: "operations",
  },
  {
    type: "mc",
    question: "Let h be defined below and let k(x) = √(x + 2). What is the domain of (h − k)(x)? Use interval notation.",
    piecewise: {
      label: "h(x) =",
      cases: [
        { expression: "2x", condition: "x ≤ 1" },
        { expression: "1/(x − 1)", condition: "x > 1" },
      ],
    },
    options: [
      "[−2, 1) ∪ (1, ∞)",
      "[−2, ∞)",
      "(−2, 1] ∪ (1, ∞)",
      "[−2, 1]",
    ],
    correctIndex: 1,
    explanation: "The piece 2x covers x ≤ 1, while 1/(x − 1) covers x > 1; hence h is defined for all real x, including x = 1 through its first piece. The radical k requires x ≥ −2. Therefore (h − k) has domain [−2, ∞), which may be written as [−2, 1] ∪ (1, ∞) to show why x = 1 is included.",
    hint: "At x = 1, use the condition of the first piece rather than the denominator in the second piece.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f be defined below and let g(x) = x. Find the domain of (f/g)(x) in interval notation.",
    piecewise: {
      label: "f(x) =",
      cases: [
        { expression: "x + 2", condition: "x < 0" },
        { expression: "3", condition: "x ≥ 0" },
      ],
    },
    answer: "(−∞, 0) ∪ (0, ∞)",
    accepted: ["(−∞, 0) ∪ (0, ∞)", "(-∞, 0) ∪ (0, ∞)", "(−∞,0)∪(0,∞)", "(-infinity,0)U(0,infinity)"],
    explanation: "The two pieces make f defined for all real inputs. In the quotient f(x)/g(x) = f(x)/x, the divisor cannot equal zero. Excluding x = 0 gives (−∞, 0) ∪ (0, ∞).",
    hint: "A quotient needs the numerator to be defined and its divisor to be nonzero.",
    visual: "operations",
  },
  {
    type: "mc",
    question: "Let f(x) = 2x − 5 and g(x) = x² + 1. What is (f + g)(3)?",
    mathLines: ["(f + g)(3) = f(3) + g(3)"],
    options: ["10", "1", "11", "16"],
    correctIndex: 2,
    explanation: "f(3) = 2(3) − 5 = 1 and g(3) = 3² + 1 = 10. Therefore (f + g)(3) = 1 + 10 = 11.",
    hint: "Evaluate each function at 3 before adding the two outputs.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f(x) = 3x + 4 and g(x) = x². Find (f − g)(−2).",
    mathLines: ["(f − g)(−2) = f(−2) − g(−2)"],
    answer: "−6",
    accepted: ["−6", "-6"],
    explanation: "f(−2) = 3(−2) + 4 = −2, and g(−2) = (−2)² = 4. Subtracting in the stated order gives (f − g)(−2) = −2 − 4 = −6.",
    hint: "The subtraction order is f's output minus g's output.",
    visual: "operations",
  },
  {
    type: "mc",
    question: "Let f(x) = 2x − 1 and g(x) = x + 3. Which expression equals (fg)(x)?",
    mathLines: ["(fg)(x) = f(x)g(x) = (2x − 1)(x + 3)"],
    options: ["2x² + 6x − 1", "2x² + 5x − 3", "2x² − 5x − 3", "3x + 2"],
    correctIndex: 1,
    explanation: "Multiply term by term: (2x − 1)(x + 3) = 2x² + 6x − x − 3 = 2x² + 5x − 3. Thus (fg)(x) = 2x² + 5x − 3.",
    hint: "Distribute both terms of the first binomial across the second binomial.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f(x) = x² − 4 and g(x) = x + 2. Simplify (f/g)(x), and state its original domain in interval notation. Enter the simplified rule followed by a semicolon and the domain.",
    mathLines: ["(f/g)(x) = (x² − 4)/(x + 2) = ((x − 2)(x + 2))/(x + 2)"],
    answer: "x − 2; (−∞, −2) ∪ (−2, ∞)",
    accepted: [
      "x − 2; (−∞, −2) ∪ (−2, ∞)",
      "x-2; (-∞, -2) ∪ (-2, ∞)",
      "x − 2;(−∞,−2)∪(−2,∞)",
      "x-2; (-infinity,-2)U(-2,infinity)",
    ],
    explanation: "Factor x² − 4 as (x − 2)(x + 2), then cancel x + 2 to get x − 2. However, the original divisor x + 2 is zero at x = −2, so that value remains excluded. The result is x − 2 with domain (−∞, −2) ∪ (−2, ∞).",
    hint: "Cancellation simplifies the formula, but it does not put a zero-denominator input back into the original domain.",
    visual: "operations",
  },
  {
    type: "mc",
    question: "At x = −1, suppose f(−1) = 5 and g(−1) = −2. What is (f − g)(−1)?",
    mathLines: ["(f − g)(−1) = f(−1) − g(−1)"],
    options: ["3", "7", "−7", "−3"],
    correctIndex: 1,
    explanation: "Subtract g's value from f's value: (f − g)(−1) = 5 − (−2) = 5 + 2 = 7.",
    hint: "Subtracting a negative is equivalent to adding its opposite.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f(x) = √x and g(x) = x − 3. Find (fg)(4).",
    mathLines: ["(fg)(4) = f(4)g(4)"],
    answer: "2",
    accepted: ["2"],
    explanation: "f(4) = √4 = 2 and g(4) = 4 − 3 = 1. Multiplying gives (fg)(4) = 2(1) = 2.",
    hint: "For a product of functions, multiply the two function values at the input.",
    visual: "operations",
  },
  {
    type: "mc",
    question: "Let f(x) = x² + 1 and g(x) = x − 2. What is (f/g)(4)?",
    mathLines: ["(f/g)(4) = f(4)/g(4)"],
    options: ["17/2", "9/2", "17", "2/17"],
    correctIndex: 0,
    explanation: "f(4) = 4² + 1 = 17 and g(4) = 4 − 2 = 2. Since g(4) is nonzero, (f/g)(4) = 17/2.",
    hint: "Evaluate the numerator function and divisor function separately, then divide.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f(x) = x + 2 and g(x) = 3x − 1. Find (2f − g)(3).",
    mathLines: ["(2f − g)(3) = 2f(3) − g(3)"],
    answer: "2",
    accepted: ["2"],
    explanation: "f(3) = 3 + 2 = 5 and g(3) = 3(3) − 1 = 8. Therefore (2f − g)(3) = 2(5) − 8 = 10 − 8 = 2.",
    hint: "The coefficient 2 applies to the entire value f(3).",
    visual: "operations",
  },
  {
    type: "mc",
    question: "Let f(x) = 1/x and g(x) = 2/(x + 1). Which expression equals (f − g)(x)?",
    mathLines: ["(f − g)(x) = 1/x − 2/(x + 1)"],
    options: [
      "(x + 3)/(x(x + 1))",
      "(1 − x)/(x(x + 1))",
      "(x − 1)/(x + 1)",
      "−1/(x(x + 1))",
    ],
    correctIndex: 1,
    explanation: "Using common denominator x(x + 1), rewrite the terms as (x + 1)/(x(x + 1)) and 2x/(x(x + 1)). Their difference is (x + 1 − 2x)/(x(x + 1)) = (1 − x)/(x(x + 1)).",
    hint: "Use x(x + 1) as a common denominator before combining the numerators.",
    visual: "operations",
  },
  {
    type: "fill",
    question: "Let f be defined below and let g(x) = x − 2. Find (f + g)(−3).",
    piecewise: {
      label: "f(x) =",
      cases: [
        { expression: "x²", condition: "x < 1" },
        { expression: "2x + 1", condition: "x ≥ 1" },
      ],
    },
    mathLines: ["(f + g)(−3) = f(−3) + g(−3)"],
    answer: "4",
    accepted: ["4"],
    explanation: "Because −3 < 1, use the first piece: f(−3) = (−3)² = 9. Also, g(−3) = −3 − 2 = −5. Hence (f + g)(−3) = 9 + (−5) = 4.",
    hint: "Choose the piece whose condition contains −3, then add the two outputs.",
    visual: "operations",
  },
];
