import type { Challenge } from "../activities";

export const quadraticSkylineBank: Challenge[] = [
  {
    type: "mc",
    question: "Which equation is in general (standard polynomial) form for a quadratic function?",
    options: [
      "f(x) = 3(x − 2)² + 1",
      "f(x) = 3x² − 12x + 13",
      "f(x) = 3(x − 2)(x + 1)",
      "f(x) = √(3x² − 12x + 13)",
    ],
    correctIndex: 1,
    explanation: "General form is f(x) = ax² + bx + c, where a ≠ 0. Only 3x² − 12x + 13 is written as ax² + bx + c with a = 3, b = −12, and c = 13.",
    hint: "Look for a quadratic written as an x² term, an x term, and a constant.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "Write f(x) = (x − 4)² − 7 in general form.",
    mathLines: ["f(x) = (x − 4)² − 7", "(x − 4)² = x² − 8x + 16"],
    answer: "x² − 8x + 9",
    accepted: ["x² − 8x + 9", "x^2 - 8x + 9", "x²-8x+9", "x^2-8x+9"],
    explanation: "Expand first: (x − 4)² = x² − 8x + 16. Then subtract 7, giving f(x) = x² − 8x + 9.",
    hint: "Square the binomial, then combine the two constant terms.",
  },
  {
    type: "mc",
    question: "What is the vertex of f(x) = −2(x − 3)² + 5?",
    options: ["(−3, 5)", "(3, −5)", "(3, 5)", "(−2, 5)"],
    correctIndex: 2,
    explanation: "Vertex form is f(x) = a(x − h)² + k, whose vertex is (h, k). Here h = 3 and k = 5, so the vertex is (3, 5).",
    hint: "In (x − h)², the vertex x-coordinate is h, not −h.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "Find the vertex of f(x) = x² − 6x + 5.",
    mathLines: ["x-coordinate of vertex = −b/(2a)", "a = 1, b = −6"],
    answer: "(3, −4)",
    accepted: ["(3, −4)", "(3,-4)", "(3, -4)"],
    explanation: "For f(x) = x² − 6x + 5, the vertex x-coordinate is −(−6)/(2·1) = 3. Evaluating gives f(3) = 9 − 18 + 5 = −4, so the vertex is (3, −4).",
    hint: "Use x = −b/(2a), then substitute that x-value back into f(x).",
    visual: "quadratic",
  },
  {
    type: "mc",
    question: "What is the axis of symmetry of f(x) = 3x² + 12x − 1?",
    options: ["x = −4", "x = −2", "x = 2", "x = 4"],
    correctIndex: 1,
    explanation: "For f(x) = ax² + bx + c, the axis is x = −b/(2a). Thus x = −12/(2·3) = −12/6 = −2.",
    hint: "Identify a = 3 and b = 12 before using x = −b/(2a).",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "Find the x-intercepts of f(x) = x² − 5x + 6. Give the intercept points.",
    mathLines: ["x² − 5x + 6 = 0", "(x − 2)(x − 3) = 0"],
    answer: "(2, 0) and (3, 0)",
    accepted: ["(2, 0) and (3, 0)", "(2,0) and (3,0)", "(2, 0), (3, 0)", "(2,0), (3,0)"],
    explanation: "An x-intercept has y = 0, so solve x² − 5x + 6 = 0. The factorization (x − 2)(x − 3) = 0 gives x = 2 or x = 3; therefore the intercepts are (2, 0) and (3, 0).",
    hint: "Set f(x) equal to zero and factor the trinomial.",
    visual: "quadratic",
  },
  {
    type: "mc",
    question: "What is the y-intercept of f(x) = −x² + 4x + 7?",
    options: ["(0, −7)", "(0, 7)", "(4, 0)", "(7, 0)"],
    correctIndex: 1,
    explanation: "A y-intercept occurs at x = 0. Since f(0) = −0² + 4(0) + 7 = 7, the y-intercept is (0, 7).",
    hint: "Substitute x = 0; the resulting output is the y-coordinate.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "For g(x) = −3(x + 2)² + 4, find g(0).",
    answer: "−8",
    accepted: ["−8", "-8"],
    explanation: "Substitute 0: g(0) = −3(0 + 2)² + 4 = −3(4) + 4 = −12 + 4 = −8.",
    hint: "Keep the parentheses when substituting 0, and square before multiplying by −3.",
  },
  {
    type: "mc",
    question: "Which equation has a graph obtained from y = x² by shifting 2 units right and 3 units up?",
    options: [
      "f(x) = (x + 2)² + 3",
      "f(x) = (x − 2)² + 3",
      "f(x) = (x − 2)² − 3",
      "f(x) = 2x² + 3",
    ],
    correctIndex: 1,
    explanation: "A horizontal shift right by 2 replaces x with x − 2, and an upward shift by 3 adds 3 outside the square. Thus f(x) = (x − 2)² + 3.",
    hint: "The sign inside the parentheses is opposite the horizontal shift direction.",
    visual: "transform",
  },
  {
    type: "fill",
    question: "A quadratic has vertex (1, −2) and passes through (3, 6). Write its equation in vertex form.",
    mathLines: ["f(x) = a(x − 1)² − 2", "6 = a(3 − 1)² − 2"],
    answer: "f(x) = 2(x − 1)² − 2",
    accepted: ["f(x) = 2(x − 1)² − 2", "f(x)=2(x−1)²−2", "f(x) = 2(x-1)^2 - 2", "f(x)=2(x-1)^2-2"],
    explanation: "Start with vertex form f(x) = a(x − 1)² − 2. Using (3, 6) gives 6 = a(2)² − 2, so 8 = 4a and a = 2. Therefore f(x) = 2(x − 1)² − 2.",
    hint: "Use the vertex to set h and k, then substitute the other point to find a.",
    visual: "quadratic",
  },
  {
    type: "mc",
    question: "What is the maximum value of f(x) = −(x + 1)² + 8?",
    options: ["−1", "0", "1", "8"],
    correctIndex: 3,
    explanation: "Because the coefficient of the squared term is negative, the parabola opens downward. Its vertex is (−1, 8), so the greatest y-value, the maximum value, is 8.",
    hint: "For a downward-opening parabola, the vertex gives the maximum y-value.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "Find the range of f(x) = −(x − 4)² + 9. Use interval notation.",
    answer: "(−∞, 9]",
    accepted: ["(−∞, 9]", "(-∞, 9]", "(-infinity, 9]", "(-infinity,9]"],
    explanation: "Since (x − 4)² ≥ 0, its negative is at most 0. Thus f(x) ≤ 9, and f(4) = 9 shows that 9 is attained. The range is (−∞, 9].",
    hint: "This parabola opens downward, so start at the vertex y-value and extend downward.",
    visual: "quadratic",
  },
  {
    type: "mc",
    question: "What is the domain of the quadratic function h(x) = 5x² − x + 2? Use interval notation.",
    options: ["(−∞, ∞)", "[0, ∞)", "(−∞, 2]", "[2, ∞)"],
    correctIndex: 0,
    explanation: "A polynomial has no denominator, radical, or other restriction on x. Therefore every real number is allowed, and the domain is (−∞, ∞).",
    hint: "Check whether any operation could make an input invalid.",
  },
  {
    type: "fill",
    question: "Find the range of p(x) = 3(x + 2)² − 1. Use interval notation.",
    answer: "[−1, ∞)",
    accepted: ["[−1, ∞)", "[-1, ∞)", "[-1, infinity)", "[-1,infinity)"],
    explanation: "The square (x + 2)² is at least 0, so 3(x + 2)² is at least 0. The smallest output is −1 at x = −2, and outputs grow without bound. Hence the range is [−1, ∞).",
    hint: "The positive leading coefficient means the vertex is the lowest point.",
    visual: "quadratic",
  },
  {
    type: "mc",
    question: "The factored form f(x) = (x + 4)(x − 2) makes which x-intercepts immediate?",
    options: ["(−4, 0) and (2, 0)", "(4, 0) and (−2, 0)", "(0, −4) and (0, 2)", "(−4, 2) and (2, −4)"],
    correctIndex: 0,
    explanation: "Set each factor equal to zero: x + 4 = 0 gives x = −4, and x − 2 = 0 gives x = 2. Since intercepts on the x-axis have y = 0, they are (−4, 0) and (2, 0).",
    hint: "At an x-intercept, the product must equal zero.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "Solve 2x² + x − 3 = 0 for x.",
    mathLines: ["2x² + x − 3 = 0", "(2x + 3)(x − 1) = 0"],
    answer: "x = 1 or x = −3/2",
    accepted: ["x = 1 or x = −3/2", "x=1 or x=-3/2", "1, −3/2", "1, -3/2"],
    explanation: "Factoring gives (2x + 3)(x − 1) = 0. By the zero-product property, 2x + 3 = 0 or x − 1 = 0, so x = −3/2 or x = 1.",
    hint: "Factor the trinomial and set each factor equal to zero.",
  },
  {
    type: "mc",
    question: "Which point lies on the graph of f(x) = (x − 1)² − 4?",
    options: ["(1, 4)", "(3, 0)", "(−1, 4)", "(0, −4)"],
    correctIndex: 1,
    explanation: "Test x = 3: f(3) = (3 − 1)² − 4 = 4 − 4 = 0. Therefore (3, 0) lies on the graph. The other listed points do not satisfy the equation.",
    hint: "Substitute each proposed x-coordinate and compare the resulting y-value.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "Rewrite f(x) = x² + 8x + 11 in vertex form.",
    mathLines: ["x² + 8x + 11 = (x² + 8x + 16) − 16 + 11", "x² + 8x + 16 = (x + 4)²"],
    answer: "f(x) = (x + 4)² − 5",
    accepted: ["f(x) = (x + 4)² − 5", "f(x)=(x+4)²−5", "f(x) = (x+4)^2 - 5", "f(x)=(x+4)^2-5"],
    explanation: "Complete the square by adding and subtracting 16: x² + 8x + 11 = (x + 4)² − 16 + 11 = (x + 4)² − 5. This is vertex form.",
    hint: "Take half of 8, square it, and balance the expression by subtracting the same number.",
  },
  {
    type: "mc",
    question: "A quadratic has x-intercepts −1 and 5 and a y-intercept of −5. Which equation is the quadratic?",
    mathLines: ["f(x) = a(x + 1)(x − 5)", "f(0) = −5"],
    options: [
      "f(x) = x² − 4x − 5",
      "f(x) = x² + 4x − 5",
      "f(x) = −x² + 4x + 5",
      "f(x) = x² − 5x − 1",
    ],
    correctIndex: 0,
    explanation: "The intercepts give f(x) = a(x + 1)(x − 5). Using f(0) = −5 gives −5a = −5, so a = 1. Expanding (x + 1)(x − 5) gives x² − 4x − 5.",
    hint: "Use the roots to make factors, then use the y-intercept to determine a.",
    visual: "quadratic",
  },
  {
    type: "fill",
    question: "Find the minimum value of f(x) = 2(x + 3)² − 7.",
    answer: "−7",
    accepted: ["−7", "-7"],
    explanation: "Because (x + 3)² ≥ 0 and 2 is positive, 2(x + 3)² ≥ 0. The smallest possible value occurs when x = −3, making the square 0; then f(−3) = −7. Thus the minimum value is −7.",
    hint: "A positive coefficient on the squared term means the vertex is the minimum.",
    visual: "quadratic",
  },
];
