import type { Challenge } from "../activities";

export const rateOfChangeLabBank: Challenge[] = [
  {
    type: "mc",
    question: "For f(x) = 3x − 5, what does the difference quotient simplify to?",
    mathLines: ["[f(x + h) − f(x)]/h"],
    options: ["3", "3h", "3x − 5", "3x + 3h − 5"],
    correctIndex: 0,
    explanation: "f(x + h) = 3(x + h) − 5 = 3x + 3h − 5. Thus [f(x + h) − f(x)]/h = [(3x + 3h − 5) − (3x − 5)]/h = 3h/h = 3, for h ≠ 0.",
    hint: "Substitute x + h everywhere that x appears before subtracting f(x).",
  },
  {
    type: "fill",
    question: "Simplify the difference quotient for the function below. Enter the expression in terms of x and h.",
    mathLines: ["f(x) = x² + 4x", "[f(x + h) − f(x)]/h"],
    answer: "2x + h + 4",
    accepted: ["2x + h + 4", "2x+h+4", "h + 2x + 4", "h+2x+4"],
    explanation: "First, f(x + h) = (x + h)² + 4(x + h) = x² + 2xh + h² + 4x + 4h. Subtracting f(x) leaves 2xh + h² + 4h = h(2x + h + 4). Dividing by h gives 2x + h + 4, for h ≠ 0.",
    hint: "Expand (x + h)², then factor h from the numerator.",
  },
  {
    type: "mc",
    question: "What is the simplified difference quotient for f(x) = x² − 6x + 1?",
    mathLines: ["[f(x + h) − f(x)]/h"],
    options: ["2x + h − 6", "2x − 6", "x² − 6x + 1", "h² − 6h + 1"],
    correctIndex: 0,
    explanation: "f(x + h) = (x + h)² − 6(x + h) + 1 = x² + 2xh + h² − 6x − 6h + 1. After subtracting x² − 6x + 1, the numerator is 2xh + h² − 6h = h(2x + h − 6). Therefore the quotient is 2x + h − 6.",
    hint: "The constant 1 cancels when you subtract f(x).",
  },
  {
    type: "fill",
    question: "Simplify the difference quotient for the cubic function.",
    mathLines: ["f(x) = 2x³ − 5", "[f(x + h) − f(x)]/h"],
    answer: "6x² + 6xh + 2h²",
    accepted: ["6x² + 6xh + 2h²", "6x^2 + 6xh + 2h^2", "2h² + 6xh + 6x²", "2h^2 + 6xh + 6x^2"],
    explanation: "Using (x + h)³ = x³ + 3x²h + 3xh² + h³, f(x + h) − f(x) = 2[(x + h)³ − x³] = 6x²h + 6xh² + 2h³. Factoring gives h(6x² + 6xh + 2h²), so division by h gives 6x² + 6xh + 2h².",
    hint: "Expand (x + h)³, or use the binomial pattern for a cube.",
  },
  {
    type: "mc",
    question: "For f(x) = −x² + 3x, which expression is the simplified difference quotient?",
    mathLines: ["[f(x + h) − f(x)]/h"],
    options: ["−2x − h + 3", "−2x + h + 3", "−x² + 3x", "−h + 3"],
    correctIndex: 0,
    explanation: "f(x + h) = −(x + h)² + 3(x + h) = −x² − 2xh − h² + 3x + 3h. Subtracting −x² + 3x leaves −2xh − h² + 3h = h(−2x − h + 3). Dividing by h yields −2x − h + 3.",
    hint: "Keep the negative sign in front of the entire square when expanding.",
  },
  {
    type: "fill",
    question: "Find and simplify the difference quotient for f(x) = 5x².",
    mathLines: ["[f(x + h) − f(x)]/h"],
    answer: "10x + 5h",
    accepted: ["10x + 5h", "10x+5h", "5h + 10x", "5h+10x"],
    explanation: "f(x + h) = 5(x + h)² = 5x² + 10xh + 5h². The numerator is (5x² + 10xh + 5h²) − 5x² = 10xh + 5h² = h(10x + 5h). Hence the quotient is 10x + 5h.",
    hint: "The 5 is multiplied by every term in the expanded square.",
  },
  {
    type: "mc",
    question: "What is the simplified difference quotient for f(x) = x³ + 2x?",
    mathLines: ["[f(x + h) − f(x)]/h"],
    options: ["3x² + 3xh + h² + 2", "3x² + 2", "x² + xh + h² + 2", "3x² + 3xh + h² + 2h"],
    correctIndex: 0,
    explanation: "f(x + h) − f(x) = [(x + h)³ + 2(x + h)] − (x³ + 2x) = 3x²h + 3xh² + h³ + 2h. Factoring h gives h(3x² + 3xh + h² + 2), so the quotient is 3x² + 3xh + h² + 2.",
    hint: "Both the cubic part and the linear part contribute terms containing h.",
  },
  {
    type: "fill",
    question: "Simplify the difference quotient for the function below.",
    mathLines: ["f(x) = x³ − x", "[f(x + h) − f(x)]/h"],
    answer: "3x² + 3xh + h² − 1",
    accepted: ["3x² + 3xh + h² − 1", "3x^2 + 3xh + h^2 - 1", "h² + 3xh + 3x² − 1", "h^2 + 3xh + 3x^2 - 1"],
    explanation: "The numerator is [(x + h)³ − (x + h)] − (x³ − x) = 3x²h + 3xh² + h³ − h. Factoring h gives h(3x² + 3xh + h² − 1). After cancellation, the simplified quotient is 3x² + 3xh + h² − 1.",
    hint: "When subtracting f(x), distribute the subtraction across both terms of x³ − x.",
  },
  {
    type: "mc",
    question: "For f(x) = 1/x, what is the simplified difference quotient?",
    mathLines: ["[f(x + h) − f(x)]/h"],
    options: ["−1/[x(x + h)]", "1/[x(x + h)]", "−1/x²", "1/h"],
    correctIndex: 0,
    explanation: "[1/(x + h) − 1/x]/h = [x − (x + h)]/[hx(x + h)] = −h/[hx(x + h)] = −1/[x(x + h)]. This requires h ≠ 0, x ≠ 0, and x + h ≠ 0.",
    hint: "Combine the two fractions in the numerator using x(x + h) as a common denominator.",
  },
  {
    type: "fill",
    question: "Simplify the difference quotient for f(x) = 2/x.",
    mathLines: ["[f(x + h) − f(x)]/h"],
    answer: "−2/[x(x + h)]",
    accepted: ["−2/[x(x + h)]", "-2/[x(x + h)]", "−2/(x(x + h))", "-2/(x(x+h))", "-2/[x(x+h)]"],
    explanation: "[2/(x + h) − 2/x]/h = [2x − 2(x + h)]/[hx(x + h)] = −2h/[hx(x + h)]. Cancelling h gives −2/[x(x + h)], with h ≠ 0, x ≠ 0, and x + h ≠ 0.",
    hint: "Write both terms with denominator x(x + h) before subtracting.",
  },
  {
    type: "mc",
    question: "What does the difference quotient simplify to for f(x) = 1/(x + 2)?",
    mathLines: ["[f(x + h) − f(x)]/h"],
    options: ["−1/[(x + 2)(x + h + 2)]", "1/[(x + 2)(x + h + 2)]", "−1/(x + 2)²", "1/[h(x + 2)]"],
    correctIndex: 0,
    explanation: "f(x + h) = 1/(x + h + 2). Combining the numerator gives [x + 2 − (x + h + 2)]/[(x + 2)(x + h + 2)] = −h/[(x + 2)(x + h + 2)]. Dividing by h leaves −1/[(x + 2)(x + h + 2)].",
    hint: "In f(x + h), replace x + 2 with x + h + 2.",
  },
  {
    type: "fill",
    question: "Use a conjugate to simplify the difference quotient for the radical function.",
    mathLines: ["f(x) = √(x + 4)", "[f(x + h) − f(x)]/h"],
    answer: "1/(√(x + h + 4) + √(x + 4))",
    accepted: ["1/(√(x + h + 4) + √(x + 4))", "1/(sqrt(x+h+4)+sqrt(x+4))", "1/[√(x + h + 4) + √(x + 4)]", "1/[sqrt(x+h+4)+sqrt(x+4)]"],
    explanation: "The quotient begins [√(x + h + 4) − √(x + 4)]/h. Multiply by the conjugate √(x + h + 4) + √(x + 4). The new numerator is (x + h + 4) − (x + 4) = h, which cancels the denominator h. The result is 1/(√(x + h + 4) + √(x + 4)).",
    hint: "Multiply the numerator and denominator by the same expression with the sign between radicals changed.",
  },
  {
    type: "mc",
    question: "For f(x) = √x, which expression is the simplified difference quotient?",
    mathLines: ["[f(x + h) − f(x)]/h"],
    options: ["1/[√(x + h) + √x]", "1/(2√x)", "[√(x + h) + √x]/h", "√h"],
    correctIndex: 0,
    explanation: "[√(x + h) − √x]/h multiplied by [√(x + h) + √x]/[√(x + h) + √x] has numerator (x + h) − x = h. Cancelling h gives 1/[√(x + h) + √x], for allowed inputs and h ≠ 0.",
    hint: "The conjugate turns a difference of square roots into a difference of radicands.",
  },
  {
    type: "fill",
    question: "Simplify the difference quotient for this rational function.",
    mathLines: ["f(x) = (x + 1)/(x − 2)", "[f(x + h) − f(x)]/h"],
    answer: "−3/[(x − 2)(x + h − 2)]",
    accepted: ["−3/[(x − 2)(x + h − 2)]", "-3/[(x - 2)(x + h - 2)]", "−3/((x − 2)(x + h − 2))", "-3/((x-2)(x+h-2))"],
    explanation: "The numerator is [(x + h + 1)/(x + h − 2)] − [(x + 1)/(x − 2)]. Combining fractions produces [(x + h + 1)(x − 2) − (x + 1)(x + h − 2)]/[(x − 2)(x + h − 2)] = −3h/[(x − 2)(x + h − 2)]. Dividing by h gives −3/[(x − 2)(x + h − 2)].",
    hint: "Use a common denominator, then expand both products in the numerator carefully.",
  },
  {
    type: "mc",
    question: "What is the simplified difference quotient for f(x) = x⁴?",
    mathLines: ["[f(x + h) − f(x)]/h"],
    options: ["4x³ + 6x²h + 4xh² + h³", "4x³", "x³ + x²h + xh² + h³", "4x³ + 6x²h + 4xh² + h⁴"],
    correctIndex: 0,
    explanation: "(x + h)⁴ − x⁴ = 4x³h + 6x²h² + 4xh³ + h⁴. Factoring h gives h(4x³ + 6x²h + 4xh² + h³). Thus the quotient is 4x³ + 6x²h + 4xh² + h³.",
    hint: "Use the binomial expansion for (x + h)⁴ and cancel x⁴.",
  },
  {
    type: "fill",
    question: "Find the simplified difference quotient for f(x) = 3x² − 2x + 7.",
    mathLines: ["[f(x + h) − f(x)]/h"],
    answer: "6x + 3h − 2",
    accepted: ["6x + 3h − 2", "6x+3h-2", "3h + 6x − 2", "3h+6x-2"],
    explanation: "f(x + h) = 3(x + h)² − 2(x + h) + 7 = 3x² + 6xh + 3h² − 2x − 2h + 7. Subtracting f(x) leaves 6xh + 3h² − 2h = h(6x + 3h − 2). Dividing by h gives 6x + 3h − 2.",
    hint: "The constant 7 will cancel, but the linear term contributes −2h.",
  },
  {
    type: "mc",
    question: "For f(x) = (x² − 9)/(x − 3), which statement correctly gives its simplified difference quotient?",
    mathLines: ["[f(x + h) − f(x)]/h"],
    options: ["It is 1 for every real x and h.", "It is 1 provided h ≠ 0, x ≠ 3, and x + h ≠ 3.", "It is (2x + h − 6)/h.", "It is undefined because the original function has a hole."],
    correctIndex: 1,
    explanation: "For inputs other than 3, f(x) = [(x − 3)(x + 3)]/(x − 3) = x + 3. Therefore f(x + h) − f(x) = (x + h + 3) − (x + 3) = h, and the quotient is 1. The original function must still be defined at both x and x + h, so x ≠ 3 and x + h ≠ 3; also h ≠ 0.",
    hint: "Factor x² − 9, but preserve the excluded input from the original denominator.",
  },
  {
    type: "fill",
    question: "Simplify the difference quotient for f(x) = (x² − 4)/(x + 2). Enter the simplified expression only.",
    mathLines: ["[f(x + h) − f(x)]/h"],
    answer: "1",
    accepted: ["1"],
    explanation: "Because x² − 4 = (x − 2)(x + 2), f(x) = x − 2 whenever x ≠ −2. Then f(x + h) − f(x) = (x + h − 2) − (x − 2) = h, and h/h = 1. This holds where h ≠ 0, x ≠ −2, and x + h ≠ −2.",
    hint: "Factor the numerator as a difference of squares before forming the quotient.",
  },
  {
    type: "mc",
    question: "Before simplifying a difference quotient for f(x) = 4x² − 3, which expression for f(x + h) is correct?",
    options: ["4(x + h)² − 3", "4x² + h − 3", "4x² + 4h² − 3", "(4x + h)² − 3"],
    correctIndex: 0,
    explanation: "To find f(x + h), replace every occurrence of x in f(x) with x + h. Thus f(x + h) = 4(x + h)² − 3. Expanding only after this substitution prevents losing the middle term 8xh.",
    hint: "The input x is replaced as a whole by the quantity x + h.",
  },
  {
    type: "fill",
    question: "Simplify the difference quotient for the function below.",
    mathLines: ["f(x) = (2x − 1)²", "[f(x + h) − f(x)]/h"],
    answer: "8x + 4h − 4",
    accepted: ["8x + 4h − 4", "8x+4h-4", "4h + 8x − 4", "4h+8x-4"],
    explanation: "f(x + h) = [2(x + h) − 1]² = (2x + 2h − 1)². Equivalently, f(x) = 4x² − 4x + 1, so f(x + h) − f(x) = 8xh + 4h² − 4h = h(8x + 4h − 4). Dividing by h gives 8x + 4h − 4.",
    hint: "You may expand (2x − 1)² first, then substitute x + h into that polynomial.",
  },
];
