import type { Challenge } from "../activities";

export const symmetryScannerBank: Challenge[] = [
  {
    type: "mc",
    question: "Classify f(x) = 3x⁶ − 2x² + 7.",
    mathLines: ["f(−x) = 3(−x)⁶ − 2(−x)² + 7"],
    options: ["Even", "Odd", "Neither", "Both even and odd"],
    correctIndex: 0,
    explanation: "Because the exponents 6 and 2 are even, f(−x) = 3x⁶ − 2x² + 7 = f(x). Therefore f is even, so its graph has y-axis symmetry.",
    hint: "Replace every x with −x and use the parity of each exponent.",
    visual: "symmetry",
  },
  {
    type: "mc",
    question: "Classify g(x) = x⁵ − 4x.",
    mathLines: ["g(−x) = (−x)⁵ − 4(−x)"],
    options: ["Even", "Odd", "Neither", "Both even and odd"],
    correctIndex: 1,
    explanation: "g(−x) = −x⁵ + 4x = −(x⁵ − 4x) = −g(x). Therefore g is odd, which corresponds to origin symmetry.",
    hint: "For an odd function, the result of substituting −x must equal −g(x).",
    visual: "symmetry",
  },
  {
    type: "mc",
    question: "Classify h(x) = x³ + x².",
    mathLines: ["h(−x) = (−x)³ + (−x)²"],
    options: ["Even", "Odd", "Neither", "Both even and odd"],
    correctIndex: 2,
    explanation: "h(−x) = −x³ + x². This is not h(x) = x³ + x², and it is not −h(x) = −x³ − x². Thus h is neither even nor odd.",
    hint: "Compare h(−x) with both h(x) and −h(x).",
    visual: "symmetry",
  },
  {
    type: "mc",
    question: "The complete graph of a function is unchanged when reflected across the y-axis. How is the function classified?",
    options: ["Even", "Odd", "Neither", "It cannot be classified from symmetry"],
    correctIndex: 0,
    explanation: "Reflection across the y-axis sends each point (x, y) to (−x, y). Thus f(−x) = f(x), which is precisely the definition of an even function.",
    hint: "A y-axis reflection keeps the output y the same.",
    visual: "symmetry",
  },
  {
    type: "mc",
    question: "A function has a domain symmetric about 0, and its complete graph is unchanged by a 180° rotation about the origin. How is it classified?",
    options: ["Even", "Odd", "Neither", "Constant"],
    correctIndex: 1,
    explanation: "A 180° rotation about the origin sends (x, y) to (−x, −y). Hence f(−x) = −f(x), so the function is odd.",
    hint: "Origin symmetry changes the signs of both coordinates.",
    visual: "symmetry",
  },
  {
    type: "mc",
    question: "The following table gives every point of a function’s graph. Classify the function.",
    mathLines: ["x: −3, −1, 1, 3", "f(x): 5, −2, −2, 5"],
    options: ["Even", "Odd", "Neither", "Both even and odd"],
    correctIndex: 0,
    explanation: "The paired inputs have equal outputs: f(−3) = f(3) = 5 and f(−1) = f(1) = −2. Thus f(−x) = f(x) at every input in its complete domain, so the function is even.",
    hint: "Compare the outputs at opposite inputs, such as −3 and 3.",
    visual: "symmetry",
  },
  {
    type: "mc",
    question: "The following table gives every point of a function’s graph. Classify the function.",
    mathLines: ["x: −2, −1, 1, 2", "f(x): −8, −1, 1, 8"],
    options: ["Even", "Odd", "Neither", "Both even and odd"],
    correctIndex: 1,
    explanation: "Opposite inputs have opposite outputs: f(−2) = −8 = −f(2), and f(−1) = −1 = −f(1). Therefore f(−x) = −f(x) throughout its complete domain, so the function is odd.",
    hint: "For odd symmetry, the outputs at x and −x must be additive inverses.",
    visual: "symmetry",
  },
  {
    type: "mc",
    question: "Using the standard definition that an even or odd function must have a domain symmetric about 0, classify q(x) = √x with domain [0, ∞).",
    options: ["Even", "Odd", "Neither", "Both even and odd"],
    correctIndex: 2,
    explanation: "The domain is [0, ∞), so, for example, 2 is allowed but −2 is not. Since the domain is not symmetric about 0, q cannot satisfy the even or odd definition; it is neither.",
    hint: "Check whether every allowed x is accompanied by −x in the domain.",
    visual: "domain",
  },
  {
    type: "mc",
    question: "Classify v using the piecewise definition shown.",
    piecewise: {
      label: "v(x) =",
      cases: [
        { expression: "x + 4", condition: "x < 0" },
        { expression: "−x + 4", condition: "x ≥ 0" },
      ],
    },
    options: ["Even", "Odd", "Neither", "Both even and odd"],
    correctIndex: 0,
    explanation: "For x > 0, v(x) = −x + 4 and v(−x) = (−x) + 4 = −x + 4. The same equality holds for negative x and at 0. Thus v(−x) = v(x), so v is even.",
    hint: "Compare the rule used at x > 0 with the rule used at −x < 0.",
    visual: "symmetry",
  },
  {
    type: "mc",
    question: "For a function whose domain contains both −2 and 2, which observation proves that it is not even?",
    options: ["f(−2) = 5 and f(2) = 5", "f(−2) = −3 and f(2) = 3", "f(−2) = 0 and f(2) = 0", "f(−2) = 7 and f(2) = 7"],
    correctIndex: 1,
    explanation: "An even function must satisfy f(−2) = f(2). In the second observation, −3 ≠ 3, so the required equality fails and the function cannot be even.",
    hint: "Even functions have matching outputs at opposite inputs.",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "Classify p(x) = 2x⁷ − x³ as even, odd, or neither.",
    mathLines: ["p(−x) = 2(−x)⁷ − (−x)³"],
    answer: "odd",
    accepted: ["odd", "Odd"],
    explanation: "p(−x) = −2x⁷ + x³ = −(2x⁷ − x³) = −p(x). Therefore p is odd and has origin symmetry.",
    hint: "Both powers are odd, so each changes sign when x is replaced by −x.",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "Classify r(x) = 5x⁴ − x² + 8 as even, odd, or neither.",
    mathLines: ["r(−x) = 5(−x)⁴ − (−x)² + 8"],
    answer: "even",
    accepted: ["even", "Even"],
    explanation: "r(−x) = 5x⁴ − x² + 8 = r(x). Thus r is even, so every graph point is mirrored across the y-axis.",
    hint: "An even power gives the same value for x and −x.",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "For f(x) = x³ − 2x, write f(−x) in simplified form.",
    mathLines: ["f(−x) = (−x)³ − 2(−x)"],
    answer: "-x³ + 2x",
    accepted: ["-x³ + 2x", "-x³+2x", "−x³ + 2x", "−x³+2x", "-x^3 + 2x", "-x^3+2x"],
    explanation: "Substitution gives f(−x) = −x³ + 2x. Since −x³ + 2x = −(x³ − 2x) = −f(x), this calculation also proves that f is odd.",
    hint: "Cube −x first, then distribute the −2.",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "Complete the graphical conclusion: If f(−x) = f(x) for every x in a domain symmetric about 0, then the graph has ___ .",
    answer: "y-axis symmetry",
    accepted: ["y-axis symmetry", "y axis symmetry", "symmetry about the y-axis", "symmetry about y-axis"],
    explanation: "The equation f(−x) = f(x) says that (−x, f(x)) appears whenever (x, f(x)) appears. Those two points are reflections across the y-axis, so the graph has y-axis symmetry.",
    hint: "The output stays unchanged when the input’s sign changes.",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "Classify s(x) = x⁴ + x as even, odd, or neither.",
    mathLines: ["s(−x) = (−x)⁴ + (−x)"],
    answer: "neither",
    accepted: ["neither", "Neither"],
    explanation: "s(−x) = x⁴ − x. This differs from s(x) = x⁴ + x and from −s(x) = −x⁴ − x. Therefore s is neither even nor odd.",
    hint: "The even-power term stays positive, while the linear term changes sign.",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "A function has domain {−3, −1, 0, 1, 3}, and its complete graph consists of the points (−3, 6), (−1, 2), (0, 0), (1, −2), and (3, −6). Classify it as even, odd, or neither.",
    answer: "odd",
    accepted: ["odd", "Odd"],
    explanation: "The graph contains origin-opposite pairs: (−3, 6) pairs with (3, −6), and (−1, 2) pairs with (1, −2); (0, 0) maps to itself. Equivalently, f(−x) = −f(x) throughout the complete domain, so the function is odd.",
    hint: "Check whether every point (x, y) is accompanied by (−x, −y).",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "Classify u using the piecewise definition shown.",
    piecewise: {
      label: "u(x) =",
      cases: [
        { expression: "−x²", condition: "x < 0" },
        { expression: "x²", condition: "x ≥ 0" },
      ],
    },
    answer: "odd",
    accepted: ["odd", "Odd"],
    explanation: "For x > 0, u(x) = x² while u(−x) = −(−x)² = −x² = −u(x). For x < 0 the same relation reverses the cases, and at x = 0 both sides are 0. Hence u(−x) = −u(x), so u is odd.",
    hint: "A positive input and its negative use different pieces; compare their outputs.",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "An odd function h has h(4) = −7. Find h(−4).",
    mathLines: ["h(−x) = −h(x)"],
    answer: "7",
    accepted: ["7"],
    explanation: "Because h is odd, h(−4) = −h(4) = −(−7) = 7. The two corresponding graph points, (4, −7) and (−4, 7), are origin-symmetric.",
    hint: "For an odd function, outputs at opposite inputs are additive inverses.",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "Classify t(x) = (x² + 1)/x on its domain (−∞, 0) ∪ (0, ∞) as even, odd, or neither.",
    mathLines: ["t(−x) = ((−x)² + 1)/(−x)"],
    answer: "odd",
    accepted: ["odd", "Odd"],
    explanation: "The domain (−∞, 0) ∪ (0, ∞) is symmetric about 0. Also, t(−x) = (x² + 1)/(−x) = −(x² + 1)/x = −t(x). Therefore t is odd.",
    hint: "The numerator does not change under −x, but the denominator does.",
    visual: "symmetry",
  },
  {
    type: "fill",
    question: "Classify c(x) = cos(x) as even, odd, or neither.",
    mathLines: ["cos(−x) = cos(x)"],
    answer: "even",
    accepted: ["even", "Even"],
    explanation: "The cosine identity cos(−x) = cos(x) shows that c(−x) = c(x) for every real x. Therefore c is even and its graph is symmetric about the y-axis.",
    hint: "Recall which basic trigonometric function has y-axis symmetry.",
    visual: "symmetry",
  },
];
