import type { Challenge } from "../activities";

export const terrainAnalyzerBank: Challenge[] = [
  {
    type: "mc",
    question: "For p(x) = −(x − 1)² + 6 on the closed interval [−2, 4], what is the global maximum point?",
    mathLines: ["p(x) = −(x − 1)² + 6", "Domain: [−2, 4]"],
    options: ["(−2, −3)", "(1, 6)", "(4, −3)", "(1, −6)"],
    correctIndex: 1,
    explanation: "Because (x − 1)² ≥ 0, −(x − 1)² ≤ 0. Thus p(x) ≤ 6 for every x in the interval, with equality when x = 1. Therefore the global maximum point is (1, 6).",
    hint: "A negative squared term is largest when the square is 0.",
    visual: "terrain",
  },
  {
    type: "fill",
    question: "Find the global minimum value (the y-value) of q(x) = (x + 1)² − 3 on [−4, 2].",
    mathLines: ["q(x) = (x + 1)² − 3", "Domain: [−4, 2]"],
    answer: "-3",
    accepted: ["-3", "−3"],
    explanation: "Since (x + 1)² ≥ 0, q(x) = (x + 1)² − 3 ≥ −3. At x = −1, the square is 0, so q(−1) = −3. Hence −3 is the global minimum value.",
    hint: "The square reaches its smallest possible value when its base is 0.",
    visual: "terrain",
  },
  {
    type: "mc",
    question: "A function is defined by h(x) = 2x − 1 on [−3, 5]. Which statement correctly identifies its global maximum?",
    mathLines: ["h(x) = 2x − 1", "Domain: [−3, 5]"],
    options: ["It occurs at (−3, −7).", "It occurs at (5, 9).", "It occurs at (0, −1).", "It has no global maximum because the rule is linear."],
    correctIndex: 1,
    explanation: "The slope 2 is positive, so h increases throughout its closed domain. Its largest input is the endpoint x = 5, and h(5) = 2(5) − 1 = 9. Thus the global maximum is at the endpoint (5, 9).",
    hint: "A positive-slope line rises as x increases; check the right endpoint.",
    visual: "terrain",
  },
  {
    type: "fill",
    question: "Find the global minimum point of r(x) = x² − 4x on [0, 5]. Enter an ordered pair.",
    mathLines: ["r(x) = x² − 4x = (x − 2)² − 4", "Domain: [0, 5]"],
    answer: "(2,-4)",
    accepted: ["(2, -4)", "(2,-4)", "(2, −4)", "(2,−4)"],
    explanation: "The completed-square form is r(x) = (x − 2)² − 4. Since (x − 2)² ≥ 0, r(x) ≥ −4, and equality occurs at x = 2. Because 2 lies in [0, 5], the global minimum point is (2, −4).",
    hint: "Use the completed-square form to locate the vertex.",
    visual: "terrain",
  },
  {
    type: "mc",
    question: "Let f(x) = x² on [0, 4]. Under the convention that a local extremum needs domain points on both sides of its x-coordinate, how should (0, 0) be classified?",
    mathLines: ["f(x) = x²", "Domain: [0, 4]"],
    options: ["It is both a global minimum and a local minimum.", "It is a global minimum, but it is not classified as a local minimum because it is an endpoint.", "It is a local minimum but not a global minimum.", "It is neither a global nor a local minimum."],
    correctIndex: 1,
    explanation: "For every x in [0, 4], x² ≥ 0, so f(0) = 0 is the global minimum value. However, x = 0 is the left endpoint of the domain, so there are no domain points to its left. It cannot be classified as a local minimum under the stated two-sided convention.",
    hint: "Global extrema may occur at endpoints; the local test in this question requires neighbors on both sides.",
    visual: "terrain",
  },
  {
    type: "fill",
    question: "For s(x) = −3x + 4 on [−2, 3], find the global maximum point. Enter an ordered pair.",
    mathLines: ["s(x) = −3x + 4", "Domain: [−2, 3]"],
    answer: "(-2,10)",
    accepted: ["(-2, 10)", "(-2,10)", "(−2, 10)", "(−2,10)"],
    explanation: "The slope is −3, so s decreases as x increases. On the closed interval, the largest output is therefore at the left endpoint: s(−2) = −3(−2) + 4 = 10. The global maximum point is (−2, 10).",
    hint: "For a decreasing function, compare the left endpoint first.",
    visual: "terrain",
  },
  {
    type: "mc",
    question: "A graph consists only of straight line segments joining the listed points in order. What is its global maximum value?",
    mathLines: ["(−3, 4), (−1, 7), (0, 1), (2, 7), (5, 3)"],
    options: ["3", "4", "7", "There is no global maximum."],
    correctIndex: 2,
    explanation: "Each line segment has y-values between the y-values of its endpoints. The largest listed endpoint y-value is 7, attained at (−1, 7) and (2, 7). No segment can exceed its endpoint values, so 7 is the global maximum value.",
    hint: "On a line segment, outputs stay between the outputs at the two ends.",
    visual: "terrain",
  },
  {
    type: "fill",
    question: "A graph consists only of straight line segments joining the listed points in order. Find its relative minimum point. Enter an ordered pair.",
    mathLines: ["(−4, 2), (−1, 5), (1, 0), (3, 4), (5, 1)"],
    answer: "(1,0)",
    accepted: ["(1, 0)", "(1,0)"],
    explanation: "The graph decreases from (−1, 5) to (1, 0), then increases from (1, 0) to (3, 4). Thus domain points immediately to the left and right of x = 1 have outputs greater than 0. Therefore (1, 0) is a relative minimum point.",
    hint: "Look for an interior point where the graph changes from decreasing to increasing.",
    visual: "terrain",
  },
  {
    type: "mc",
    question: "Which statement correctly describes the global maximum of the piecewise function?",
    piecewise: {
      label: "f(x) =",
      cases: [
        { expression: "x + 4", condition: "−4 ≤ x < −1" },
        { expression: "3", condition: "−1 ≤ x ≤ 1" },
        { expression: "−x + 4", condition: "1 < x ≤ 4" },
      ],
    },
    options: ["The global maximum value is 4 at x = 0.", "The global maximum value is 3 at every x in [−1, 1].", "The global maximum point is only (−1, 3).", "There is no global maximum because the function is piecewise."],
    correctIndex: 1,
    explanation: "On −4 ≤ x < −1, x + 4 is less than 3. On −1 ≤ x ≤ 1, f(x) = 3. On 1 < x ≤ 4, −x + 4 is less than 3. Hence the largest y-value is 3, attained for every x in [−1, 1].",
    hint: "Check the possible outputs from each branch, including whether boundary values are included.",
    visual: "piecewise",
  },
  {
    type: "fill",
    question: "Find the global maximum point of the piecewise function. Enter an ordered pair.",
    piecewise: {
      label: "v(x) =",
      cases: [
        { expression: "x + 2", condition: "−2 ≤ x < 0" },
        { expression: "2 − x", condition: "0 ≤ x ≤ 2" },
      ],
    },
    answer: "(0,2)",
    accepted: ["(0, 2)", "(0,2)"],
    explanation: "For −2 ≤ x < 0, x + 2 is less than 2 but approaches 2. At x = 0, the second branch applies and v(0) = 2. For 0 ≤ x ≤ 2, 2 − x ≤ 2. Thus the highest included output is 2 at x = 0, so the global maximum point is (0, 2).",
    hint: "Pay close attention to which branch includes x = 0.",
    visual: "piecewise",
  },
  {
    type: "mc",
    question: "On which intervals is the piecewise function strictly increasing?",
    piecewise: {
      label: "m(x) =",
      cases: [
        { expression: "x + 5", condition: "−5 ≤ x < −2" },
        { expression: "−x + 1", condition: "−2 ≤ x < 1" },
        { expression: "0", condition: "1 ≤ x ≤ 3" },
        { expression: "2x − 6", condition: "3 < x ≤ 5" },
      ],
    },
    options: ["[−5, −2] ∪ [3, 5]", "[−2, 1] ∪ [1, 3]", "[−5, 5]", "[1, 3]"],
    correctIndex: 0,
    explanation: "The rule x + 5 has positive slope on [−5, −2], and 2x − 6 has positive slope beginning at x = 3, where m(3) = 0, through x = 5. The rule −x + 1 decreases, while the rule 0 is constant. Therefore m is strictly increasing on [−5, −2] ∪ [3, 5].",
    hint: "Positive slope means increasing; zero slope means constant.",
    visual: "piecewise",
  },
  {
    type: "fill",
    question: "Give the interval on which the piecewise function is decreasing. Use interval notation.",
    piecewise: {
      label: "n(x) =",
      cases: [
        { expression: "−x − 3", condition: "−4 ≤ x < −1" },
        { expression: "x − 1", condition: "−1 ≤ x ≤ 2" },
        { expression: "1", condition: "2 < x ≤ 4" },
      ],
    },
    answer: "[-4,-1]",
    accepted: ["[−4, −1]", "[-4, -1]", "[-4,-1]", "[−4,−1]"],
    explanation: "On [−4, −1], the rule −x − 3 has slope −1, so outputs decrease as x increases; the value at x = −1 is supplied by the next branch and continues the decrease. The rule x − 1 increases on [−1, 2], and the last rule is constant. Thus the decreasing interval is [−4, −1].",
    hint: "A linear rule with a negative coefficient of x is decreasing.",
    visual: "piecewise",
  },
  {
    type: "mc",
    question: "On which interval is the piecewise function constant?",
    piecewise: {
      label: "a(x) =",
      cases: [
        { expression: "2x + 4", condition: "−3 ≤ x < 0" },
        { expression: "4", condition: "0 ≤ x ≤ 3" },
        { expression: "7 − x", condition: "3 < x ≤ 6" },
      ],
    },
    options: ["[−3, 0]", "[0, 3]", "[3, 6]", "[−3, 6]"],
    correctIndex: 1,
    explanation: "The middle branch gives a(x) = 4 for every x from 0 through 3, so its output does not change on [0, 3]. The first and third branches have nonzero slopes, so they are not constant.",
    hint: "Find the branch whose expression does not contain x.",
    visual: "piecewise",
  },
  {
    type: "fill",
    question: "Give the interval on which u(x) = (x − 1)² is decreasing when its domain is restricted to [−2, 4]. Use interval notation.",
    mathLines: ["u(x) = (x − 1)²", "Domain: [−2, 4]"],
    answer: "[-2,1]",
    accepted: ["[−2, 1]", "[-2, 1]", "[-2,1]", "[−2,1]"],
    explanation: "The vertex is at x = 1. As x moves from −2 toward 1, the distance |x − 1| decreases, so its square decreases. After x = 1, the distance increases. Therefore u is decreasing on [−2, 1].",
    hint: "A parabola opening upward decreases to its vertex and increases after it.",
    visual: "terrain",
  },
  {
    type: "mc",
    question: "For w(x) = |x + 2| on [−6, 3], which interval is decreasing?",
    mathLines: ["w(x) = |x + 2|", "Domain: [−6, 3]"],
    options: ["[−6, −2]", "[−2, 3]", "[−6, 3]", "[−2, −6]"],
    correctIndex: 0,
    explanation: "The absolute-value graph has its vertex at x = −2. Moving from −6 to −2 makes x closer to −2, so |x + 2| decreases. Moving right of −2 makes the value increase. Hence the decreasing interval is [−6, −2].",
    hint: "Locate the V-shaped graph's vertex first.",
    visual: "terrain",
  },
  {
    type: "fill",
    question: "A function is defined by c(x) = 7 on [−3, 5]. Give its constant interval in interval notation.",
    mathLines: ["c(x) = 7", "Domain: [−3, 5]"],
    answer: "[-3,5]",
    accepted: ["[−3, 5]", "[-3, 5]", "[-3,5]", "[−3,5]"],
    explanation: "Every input in the stated domain produces the same output, 7. Since c does not change anywhere from −3 through 5, it is constant on [−3, 5].",
    hint: "A constant rule has the same y-value for every allowed x.",
    visual: "terrain",
  },
  {
    type: "mc",
    question: "A graph consists only of straight line segments joining the listed points in order. Which list gives all relative maximum points, using the two-sided local-extremum convention?",
    mathLines: ["(−4, 0), (−2, 3), (0, 1), (2, 4), (4, 0)"],
    options: ["(−4, 0) and (4, 0)", "(−2, 3) and (2, 4)", "(0, 1) only", "(2, 4) only"],
    correctIndex: 1,
    explanation: "At (−2, 3), the graph changes from increasing to decreasing, so nearby points on both sides have smaller outputs. At (2, 4), it again changes from increasing to decreasing. The endpoints are not local extrema under the stated two-sided convention. Thus the relative maximum points are (−2, 3) and (2, 4).",
    hint: "Relative maxima are interior peaks: the graph rises before them and falls after them.",
    visual: "terrain",
  },
  {
    type: "fill",
    question: "Find the relative maximum value (the y-value) of t(x) = −(x − 1)² + 3 on [−1, 4].",
    mathLines: ["t(x) = −(x − 1)² + 3", "Domain: [−1, 4]"],
    answer: "3",
    accepted: ["3"],
    explanation: "Because (x − 1)² ≥ 0, t(x) = −(x − 1)² + 3 ≤ 3. Equality occurs at x = 1, which is an interior point of [−1, 4], so nearby values on both sides are lower. The relative maximum value is 3.",
    hint: "The vertex of a downward-opening parabola is its peak.",
    visual: "terrain",
  },
  {
    type: "mc",
    question: "Let b(x) = 5 − (x − 2)² on [2, 6]. Under the convention that a local extremum needs domain points on both sides, which statement about (2, 5) is correct?",
    mathLines: ["b(x) = 5 − (x − 2)²", "Domain: [2, 6]"],
    options: ["It is both a global maximum and a local maximum.", "It is a global maximum but not a local maximum because it is an endpoint.", "It is a local maximum but not a global maximum.", "It is neither a global nor a local maximum."],
    correctIndex: 1,
    explanation: "Since (x − 2)² ≥ 0, b(x) ≤ 5 for every x in [2, 6], and b(2) = 5. Thus (2, 5) is a global maximum. But x = 2 is the left endpoint, so it lacks domain points on its left and is not classified as a local maximum under the stated two-sided convention.",
    hint: "Separate the global comparison over the whole domain from the two-sided local requirement.",
    visual: "terrain",
  },
  {
    type: "fill",
    question: "Find the global minimum point of k(x) = (x − 5)² + 1 on [5, 9]. Enter an ordered pair.",
    mathLines: ["k(x) = (x − 5)² + 1", "Domain: [5, 9]"],
    answer: "(5,1)",
    accepted: ["(5, 1)", "(5,1)"],
    explanation: "The square (x − 5)² is always nonnegative, so k(x) ≥ 1. At the endpoint x = 5, the square is 0 and k(5) = 1. Hence the global minimum point is (5, 1); a global extremum may occur at an endpoint of a closed domain.",
    hint: "The smallest possible square is 0; check whether its x-value belongs to the interval.",
    visual: "terrain",
  },
];
