import type { Challenge } from "../activities";

export const transformationBayBank: Challenge[] = [
  {
    type: "mc",
    question: "Let g(x) = f(x) + 6. Relative to the graph of f, how is the graph of g transformed?",
    options: [
      "6 units down",
      "6 units up",
      "6 units right",
      "6 units left",
    ],
    correctIndex: 1,
    explanation: "Adding 6 outside f changes every output from y to y + 6. Thus every point moves 6 units upward.",
    hint: "A number added outside a function affects y-values.",
  },
  {
    type: "fill",
    question: "Let g(x) = f(x − 4). Describe the horizontal translation from f to g.",
    answer: "4 units right",
    accepted: ["4 units right", "right 4 units", "4 right"],
    explanation: "For g(x) = f(x − 4), an old input a occurs when x − 4 = a, so it occurs at x = a + 4. Every feature therefore moves 4 units right.",
    hint: "Set the expression inside f equal to an old input a.",
  },
  {
    type: "mc",
    question: "Let g(x) = f(2(x + 3)). Which description of the transformation from f to g is correct?",
    options: [
      "Translate 3 units left, then stretch horizontally by a factor of 2.",
      "Translate 3 units right, then compress horizontally by a factor of 1/2.",
      "Translate 3 units left, then stretch vertically by a factor of 2.",
      "Compress horizontally by a factor of 1/2, then translate 3 units left.",
    ],
    correctIndex: 3,
    explanation: "For an old point with x-coordinate a, solve 2(x + 3) = a; this gives x = a/2 − 3. Thus horizontal distances are first divided by 2, then the result shifts 3 units left.",
    hint: "Factors multiplying x inside f have reciprocal horizontal effects.",
  },
  {
    type: "fill",
    question: "Let r(x) = f(−x). Across which axis is the graph of f reflected to obtain r?",
    answer: "y-axis",
    accepted: ["y-axis", "y axis", "the y-axis", "the y axis"],
    explanation: "If (a, f(a)) is on f, then r(−a) = f(−(−a)) = f(a). The x-coordinate changes sign while the y-coordinate stays the same, which is reflection across the y-axis.",
    hint: "The negative sign is inside the function input.",
  },
  {
    type: "mc",
    question: "Let h(x) = −f(x) + 2. Which sequence transforms the graph of f into the graph of h?",
    options: [
      "Reflect across the y-axis, then move 2 units up.",
      "Reflect across the x-axis, then move 2 units down.",
      "Reflect across the x-axis, then move 2 units up.",
      "Reflect across the line y = x, then move 2 units up.",
    ],
    correctIndex: 2,
    explanation: "The factor −1 outside f sends each output y to −y, reflecting across the x-axis. Adding 2 then sends −y to −y + 2, moving the reflected graph up 2 units.",
    hint: "Signs outside f affect y-values.",
  },
  {
    type: "fill",
    question: "Let g(x) = 3f(x). Describe the stretch or compression from f to g.",
    answer: "vertical stretch by a factor of 3",
    accepted: ["vertical stretch by a factor of 3", "vertical stretch factor 3", "vertical stretch of 3", "vertical stretch 3"],
    explanation: "For every point (a, b) on f, the corresponding point on g is (a, 3b). The x-coordinate is unchanged and each y-value is tripled, so this is a vertical stretch by factor 3.",
    hint: "A multiplier outside f scales outputs.",
  },
  {
    type: "mc",
    question: "Let g(x) = f(4x). What is the horizontal effect on the graph of f?",
    options: [
      "A horizontal stretch by a factor of 4",
      "A horizontal compression by a factor of 1/4",
      "A vertical stretch by a factor of 4",
      "A translation 4 units right",
    ],
    correctIndex: 1,
    explanation: "To match an old input a, solve 4x = a, giving x = a/4. Every x-coordinate is divided by 4, so the graph is horizontally compressed by factor 1/4.",
    hint: "Inside factors use their reciprocals for horizontal scaling.",
  },
  {
    type: "fill",
    question: "Let g(x) = f(x/5). Describe the horizontal stretch or compression from f to g.",
    answer: "horizontal stretch by a factor of 5",
    accepted: ["horizontal stretch by a factor of 5", "horizontal stretch factor 5", "horizontal stretch of 5", "horizontal stretch 5"],
    explanation: "An old input a is reached when x/5 = a, or x = 5a. Each x-coordinate is multiplied by 5, so the graph has a horizontal stretch by factor 5.",
    hint: "The inside multiplier is 1/5, so use its reciprocal.",
  },
  {
    type: "mc",
    question: "A point (a, b) lies on the graph of f. If g(x) = −2f(x − 3) + 1, which point must lie on the graph of g?",
    options: [
      "(a − 3, −2b + 1)",
      "(a + 3, 2b + 1)",
      "(a − 3, −2b − 1)",
      "(a + 3, −2b + 1)",
    ],
    correctIndex: 3,
    explanation: "Choose x = a + 3 so that x − 3 = a. Then g(a + 3) = −2f(a) + 1 = −2b + 1. Thus (a + 3, −2b + 1) is on g.",
    hint: "Make the inside input x − 3 equal to a first.",
  },
  {
    type: "fill",
    question: "The point (2, −1) is on f. Let g(x) = f(−x) + 4. Give the corresponding point on g as an ordered pair.",
    answer: "(−2, 3)",
    accepted: ["(−2, 3)", "(-2, 3)", "(−2,3)", "(-2,3)"],
    mathLines: ["g(−2) = f(−(−2)) + 4", "g(−2) = f(2) + 4 = −1 + 4 = 3"],
    explanation: "The input reflection sends x = 2 to x = −2. The outside +4 sends the y-value −1 to 3, so the corresponding point is (−2, 3).",
    hint: "Use x = −2 so the input to f becomes 2.",
  },
  {
    type: "fill",
    question: "The domain of f is [−2, 4]. If g(x) = f(x + 3), find the domain of g. Use interval notation.",
    answer: "[−5, 1]",
    accepted: ["[−5, 1]", "[-5, 1]", "[−5,1]", "[-5,1]"],
    mathLines: ["x + 3 ∈ [−2, 4]", "x ∈ [−5, 1]"],
    explanation: "The input x + 3 must be an allowed input of f. Shifting the interval [−2, 4] left by 3 gives the domain [−5, 1].",
    hint: "The expression fed to f must stay in f’s domain.",
  },
  {
    type: "mc",
    question: "The range of f is [−1, 5]. If h(x) = −f(x) + 2, what is the range of h? Use interval notation.",
    options: ["[1, 7]", "[−3, 3]", "[−7, −1]", "[−5, 1]"],
    correctIndex: 1,
    mathLines: ["[−1, 5] → [−5, 1]  after multiplying outputs by −1", "[−5, 1] → [−3, 3]  after adding 2"],
    explanation: "Reflecting the output interval [−1, 5] across the x-axis gives [−5, 1]. Moving those outputs up 2 gives the range [−3, 3].",
    hint: "Apply the outside operations to the interval of y-values.",
  },
  {
    type: "mc",
    question: "The graph y = (x + 4)² − 2 is obtained from the parent graph y = x². What is the vertex of the transformed graph?",
    options: ["(4, −2)", "(−4, 2)", "(−4, −2)", "(2, −4)"],
    correctIndex: 2,
    explanation: "The x + 4 inside the square shifts the parent vertex 4 units left, from x = 0 to x = −4. The −2 outside shifts it down 2, so the vertex is (−4, −2).",
    hint: "Inside additions shift in the opposite horizontal direction.",
  },
  {
    type: "fill",
    question: "Start with f(x) = √x. Translate its graph 3 units right, then reflect it across the x-axis. Write the resulting function g(x).",
    answer: "−√(x − 3)",
    accepted: ["−√(x − 3)", "-√(x − 3)", "-sqrt(x-3)", "−sqrt(x−3)"],
    mathLines: ["right 3:  f(x − 3) = √(x − 3)", "reflect across x-axis:  g(x) = −√(x − 3)"],
    explanation: "A right translation replaces x by x − 3, producing √(x − 3). Reflection across the x-axis negates all outputs, producing g(x) = −√(x − 3).",
    hint: "Right is x − 3 inside; an x-axis reflection puts a negative sign outside.",
  },
  {
    type: "mc",
    question: "Let f(x) = √x and g(x) = f(−x). What is the domain of g? Use interval notation.",
    options: ["[0, ∞)", "(−∞, 0]", "(−∞, ∞)", "[0, ∞]"],
    correctIndex: 1,
    explanation: "Here g(x) = √(−x). The inputs that make the radicand valid extend indefinitely to the left and include 0, so the domain is (−∞, 0].",
    hint: "Reflecting y = √x across the y-axis moves its domain to the left of the origin.",
  },
  {
    type: "fill",
    question: "The graph y = √(3x − 6) is obtained from y = √x. Describe its horizontal transformations in the order shown by the expression.",
    answer: "horizontal compression by a factor of 1/3, then 2 units right",
    accepted: [
      "horizontal compression by a factor of 1/3, then 2 units right",
      "horizontal compression factor 1/3, then 2 units right",
      "compress horizontally by 1/3, then shift right 2",
    ],
    mathLines: ["√(3x − 6) = √(3(x − 2))", "f(x) → f(3x) → f(3(x − 2))"],
    explanation: "The factor 3 inside first compresses the parent graph horizontally by factor 1/3. Replacing x with x − 2 then translates that compressed graph 2 units right.",
    hint: "Factor the inside expression before interpreting it.",
  },
  {
    type: "mc",
    question: "For the function p defined below, let q(x) = p(x − 2). What is q(1)?",
    piecewise: {
      label: "p(x) =",
      cases: [
        { expression: "2x + 1", condition: "x < 0" },
        { expression: "x² − 1", condition: "x ≥ 0" },
      ],
    },
    options: ["−1", "0", "1", "2"],
    correctIndex: 0,
    mathLines: ["q(1) = p(1 − 2)", "q(1) = p(−1) = 2(−1) + 1 = −1"],
    explanation: "Because 1 − 2 = −1, use the first piece of p. It gives p(−1) = 2(−1) + 1 = −1, so q(1) = −1.",
    hint: "Evaluate the inside input 1 − 2 before choosing a piece.",
  },
  {
    type: "fill",
    question: "For the function p defined below, let r(x) = −p(−x). Find r(−2).",
    piecewise: {
      label: "p(x) =",
      cases: [
        { expression: "x + 3", condition: "x < 1" },
        { expression: "2x − 1", condition: "x ≥ 1" },
      ],
    },
    answer: "−3",
    accepted: ["−3", "-3"],
    mathLines: ["r(−2) = −p(−(−2))", "r(−2) = −p(2) = −(2(2) − 1) = −3"],
    explanation: "The inside reflection changes −2 to 2, which uses the second piece: p(2) = 2(2) − 1 = 3. The outside negative then gives r(−2) = −3.",
    hint: "Apply the input negative before selecting the piece, then apply the output negative.",
  },
  {
    type: "mc",
    question: "Let g(x) = f(2x + 6). Which transformation description is correct?",
    options: [
      "Translate 3 units right, then compress horizontally by a factor of 1/2.",
      "Translate 6 units left, then compress horizontally by a factor of 1/2.",
      "Translate 3 units left, then stretch horizontally by a factor of 2.",
      "Compress horizontally by a factor of 1/2, then translate 3 units left.",
    ],
    correctIndex: 3,
    mathLines: ["g(x) = f(2x + 6)", "g(x) = f(2(x + 3))"],
    explanation: "Factoring gives 2(x + 3). If a is an old input, 2(x + 3) = a gives x = a/2 − 3. Therefore the graph is compressed horizontally by factor 1/2 and then translated 3 units left.",
    hint: "Factor out the coefficient of x before reading the translation.",
  },
  {
    type: "fill",
    question: "Start with f(x) = x². Reflect its graph across the x-axis, stretch it vertically by a factor of 2, translate it 4 units left, and then 3 units up. Write the final function g(x).",
    answer: "−2(x + 4)² + 3",
    accepted: ["−2(x + 4)² + 3", "-2(x + 4)^2 + 3", "-2(x+4)^2+3", "−2(x+4)²+3"],
    mathLines: ["x² → −x² → −2x²", "−2x² → −2(x + 4)² → −2(x + 4)² + 3"],
    explanation: "Reflection across the x-axis and a vertical stretch by 2 produce −2x². A left shift of 4 replaces x by x + 4, and adding 3 moves the graph up, giving g(x) = −2(x + 4)² + 3.",
    hint: "A left translation uses x + 4 inside the squared expression.",
  },
];
